Repository kubeflow/examples, pull requests merged in 2018-03, with the labels that each got.

#24 Create an initial OWNERS file.
  OWNERS
Labels: lgtm, size/S

#23 Create a end-to-end kubeflow example using seq2seq model (2/n)
  issue_summarization_github_issues/README.md
  issue_summarization_github_issues/notebooks/Tutorial.ipynb
  issue_summarization_github_issues/setup_a_kubeflow_cluster.md
  issue_summarization_github_issues/training_the_model.md
Labels: approved, size/XXL

#19 Move example to third_party folder
  github_issue_summarization/README.md
  github_issue_summarization/notebooks/Tutorial.ipynb
  github_issue_summarization/notebooks/seq2seq_utils.py
  github_issue_summarization/requirements.txt
  github_issue_summarization/setup_a_kubeflow_cluster.md
  github_issue_summarization/sql/GetIssues.sql
  github_issue_summarization/teardown.md
  github_issue_summarization/training_the_model.md
Labels: approved, lgtm, size/XS

#22 Add a .gitignore
  .gitignore
Labels: size/M

#18 Skeleton testing framework
  prow_config.yaml
  test/workflows/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/test/.metadata/k.libsonnet
  test/workflows/environments/test/.metadata/k8s.libsonnet
  test/workflows/environments/test/.metadata/swagger.json
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/environments/test/spec.json
Labels: approved, lgtm, size/XXL

#6 Contributing
  CONTRIBUTING.md
Labels: lgtm, size/M

#31 Create a end-to-end kubeflow example using seq2seq model (3/n)
  github_issue_summarization/README.md
  github_issue_summarization/notebooks/server.py
  github_issue_summarization/serving_the_model.md
Labels: approved, lgtm, size/M

#35 Example workflow for Github issue summarization.
  github_issue_summarization/workflow/Dockerfile
  github_issue_summarization/workflow/README.md
  github_issue_summarization/workflow/github_issues_summarization.yaml
  github_issue_summarization/workflow/workspace/src/prediction.py
  github_issue_summarization/workflow/workspace/src/preprocess_data_for_deep_learning.py
  github_issue_summarization/workflow/workspace/src/process_data.py
  github_issue_summarization/workflow/workspace/src/recommend.py
  github_issue_summarization/workflow/workspace/src/seq2seq_utils.py
  github_issue_summarization/workflow/workspace/src/train.py
Labels: approved, lgtm, size/XL

#36 Move from a custom tornado server to a seldon-core server for serving the model
  .gitignore
  github_issue_summarization/README.md
  github_issue_summarization/notebooks/IssueSummarization.py
  github_issue_summarization/notebooks/requirements.txt
  github_issue_summarization/notebooks/server.py
  github_issue_summarization/serving_the_model.md
Labels: approved, lgtm, size/L

#30 Reinforcement learning example with TensorFlow Agents
  agents/Dockerfile
  agents/README.md
  agents/app/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  agents/app/.ksonnet/registries/kubeflow/d7d859206f52168665cbc312391c67c162927e96.yaml
  agents/app/app.yaml
  agents/app/components/agents.jsonnet
  agents/app/components/agents_render.jsonnet
  agents/app/components/params.libsonnet
  agents/app/components/tensorboard.jsonnet
  agents/app/components/tensorboard.libsonnet
  agents/app/environments/base.libsonnet
  agents/doc/builder.png
  agents/doc/demo.ipynb
  agents/doc/jhub-spawn.png
  agents/doc/render.mp4
  agents/doc/render_preview.png
  agents/doc/sa-create.png
  agents/doc/tboard_mean_score.png
  agents/requirements.txt
  agents/tools/builder/Dockerfile
  agents/tools/builder/README.md
  agents/tools/builder/builder.yaml
  agents/tools/release/envless_commit.sh
  agents/tools/release/release_demo_container.sh
  agents/trainer/__init__.py
  agents/trainer/task.py
Labels: approved, lgtm, size/XXL

#44 Add detail to cluster setup instructions
  README.md
  github_issue_summarization/notebooks/Tutorial.ipynb
  github_issue_summarization/setup_a_kubeflow_cluster.md
Labels: approved, lgtm, size/M

#47 Add file copy instructions after training
  github_issue_summarization/notebooks/Training.ipynb
  github_issue_summarization/setup_a_kubeflow_cluster.md
  github_issue_summarization/training_the_model.md
Labels: approved, lgtm, size/M

#49 ks upgrade test/workflows and agents/app
  agents/app/app.yaml
  test/workflows/app.yaml
  test/workflows/environments/test/spec.json
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#46 Add instructions to deploy the seldon core model
  github_issue_summarization/serving_the_model.md
Labels: approved, lgtm, size/M

#51 Update seq2seq_utils.py - Fixed call to `corpus_bleu`
  github_issue_summarization/notebooks/seq2seq_utils.py
Labels: approved, lgtm, size/XS

#52 Update Training.ipynb
  github_issue_summarization/notebooks/Training.ipynb
Labels: approved, lgtm, size/L

#53 [GitHub Issue Summarization] (very) simple front-end web app
  github_issue_summarization/README.md
  github_issue_summarization/docker/Dockerfile
  github_issue_summarization/docker/flask_web/app.py
  github_issue_summarization/docker/flask_web/requirements.txt
  github_issue_summarization/docker/flask_web/templates/index.html
  github_issue_summarization/docker/flask_web/templates/summary.html
  github_issue_summarization/querying_the_model.md
  github_issue_summarization/serving_the_model.md
Labels: approved, lgtm, size/L

#61 Add .pylintrc
  .pylintrc
  agents/trainer/task.py
  github_issue_summarization/docker/flask_web/app.py
  github_issue_summarization/notebooks/IssueSummarization.py
  github_issue_summarization/notebooks/issue_summarization.py
  github_issue_summarization/notebooks/seq2seq_utils.py
  github_issue_summarization/workflow/workspace/src/prediction.py
  github_issue_summarization/workflow/workspace/src/preprocess_data_for_deep_learning.py
  github_issue_summarization/workflow/workspace/src/process_data.py
  github_issue_summarization/workflow/workspace/src/recommend.py
  github_issue_summarization/workflow/workspace/src/seq2seq_utils.py
  github_issue_summarization/workflow/workspace/src/train.py
Labels: approved, lgtm, size/XXL

#64 OWNERS Add cwbeitel reviewer & texasmichelle approver
  OWNERS
Labels: approved, lgtm, size/XS

#65 Move from mlkube-testing to kubeflow-ci for test-infra
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S
