Repository kubeflow/examples, pull requests merged in 2018-07, with the labels that each got.

#159 Add similarity transformer body
  code_search/README.md
  code_search/app/code_search/t2t/__init__.py
  code_search/app/code_search/t2t/function_docstring.py
  code_search/app/code_search/t2t/similarity_transformer.py
  code_search/preprocess/preprocess/pipeline.py
  code_search/preprocess/requirements.txt
  code_search/preprocess/scripts/process_github_archive.py
Labels: approved, lgtm, size/L

#74 Added tutorial for object detection distributed training
  CONTRIBUTING.md
  README.md
  object_detection/README.md
  object_detection/conf/faster_rcnn_resnet101_pets.config
  object_detection/docker/Dockerfile
  object_detection/export_tf_graph.md
  object_detection/jobs/00create-pvc.yaml
  object_detection/jobs/01get-dataset.yaml
  object_detection/jobs/02get-annotations.yaml
  object_detection/jobs/03get-model-job.yaml
  object_detection/jobs/04decompress-images.yaml
  object_detection/jobs/05decompress-annotations.yaml
  object_detection/jobs/06decompress-model.yaml
  object_detection/jobs/07get-fasterrcnn-config.yaml
  object_detection/jobs/08create-pet-record.yaml
  object_detection/jobs/export-tf-graph.yaml
  object_detection/jobs/pets-training.yaml
  object_detection/monitor_job.md
  object_detection/setup.md
  object_detection/submit_job.md
  object_detection/tf-serving/tf-serving.yaml
Labels: approved, lgtm, size/XL

#167 Add negative sampling to Transformer network
  code_search/app/code_search/t2t/similarity_transformer.py
  code_search/kubeflow/components/t2t-job.libsonnet
Labels: approved, lgtm, size/S

#168 Search UI Components
  code_search/ui/.gitignore
  code_search/ui/Dockerfile
  code_search/ui/README.md
  code_search/ui/package-lock.json
  code_search/ui/package.json
  code_search/ui/public/favicon.ico
  code_search/ui/public/index.html
  code_search/ui/public/manifest.json
  code_search/ui/src/App.css
  code_search/ui/src/App.js
  code_search/ui/src/App.test.js
  code_search/ui/src/CodeSample.js
  code_search/ui/src/CodeSearchApi.js
  code_search/ui/src/index.css
  code_search/ui/src/index.js
  code_search/ui/src/logo.svg
  code_search/ui/src/registerServiceWorker.js
  code_search/ui/src/theme.js
Labels: approved, lgtm, size/XXL

#161 Create a deployment to run the HP/Katib controller for the GitHub issue example
  .gitignore
  github_issue_summarization/hp-tune/Dockerfile
  github_issue_summarization/hp-tune/Gopkg.lock
  github_issue_summarization/hp-tune/Gopkg.toml
  github_issue_summarization/hp-tune/Makefile
  github_issue_summarization/hp-tune/README.md
  github_issue_summarization/hp-tune/git-issue-summarize-demo.go
  github_issue_summarization/ks-kubeflow/components/hp-tune.jsonnet
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
Labels: approved, lgtm, size/XL

#119 Update PVC to /home/jovyan
  agents/doc/demo.ipynb
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/scripts/1_setup_kubeflow.sh
Labels: approved, lgtm, size/XS

#177 Update decompress config to avoid error, fix typo
  object_detection/jobs/04decompress-images.yaml
  object_detection/jobs/05decompress-annotations.yaml
  object_detection/jobs/06decompress-model.yaml
  object_detection/jobs/07get-fasterrcnn-config.yaml
Labels: approved, lgtm, size/S

#169 Fix transformer export
  code_search/app/code_search/nmslib/cli.py
  code_search/app/code_search/nmslib/gcs.py
  code_search/app/code_search/nmslib/search_engine.py
  code_search/app/code_search/nmslib/search_server.py
  code_search/app/code_search/t2t/function_docstring.py
  code_search/app/code_search/t2t/similarity_transformer.py
Labels: approved, lgtm, size/M

#183 Update pets-training to v1alpha2
  object_detection/jobs/pets-training.yaml
Labels: approved, lgtm, size/L

#194 Integrate nmslib
  code_search/src/code_search/nmslib/cli.py
  code_search/src/code_search/nmslib/search_engine.py
  code_search/src/code_search/nmslib/search_server.py
  code_search/src/requirements.txt
  code_search/ui/package-lock.json
  code_search/ui/package.json
  code_search/ui/src/App.js
  code_search/ui/src/CodeSample.js
  code_search/ui/src/CodeSearchApi.js
Labels: approved, lgtm, size/L

#193 fix typo in OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#154 Example of TF Serving with GPU
  object_detection/README.md
  object_detection/export_tf_graph.md
  object_detection/ks-app/.gitignore
  object_detection/ks-app/app.yaml
  object_detection/ks-app/components/model1.jsonnet
  object_detection/ks-app/components/params.libsonnet
  object_detection/ks-app/vendor/kubeflow/tf-serving/README.md
  object_detection/ks-app/vendor/kubeflow/tf-serving/parts.yaml
  object_detection/ks-app/vendor/kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet
  object_detection/ks-app/vendor/kubeflow/tf-serving/tf-serving.libsonnet
  object_detection/ks-app/vendor/kubeflow/tf-serving/util.libsonnet
  object_detection/serving_script/image1.jpg
  object_detection/serving_script/predict.py
  object_detection/serving_script/standard_fields.py
  object_detection/serving_script/visualization_utils.py
  object_detection/tf-serving/tf-serving.yaml
  object_detection/tf_serving_gpu.md
Labels: approved, lgtm, size/XXL
