Repository kubeflow/examples, pull requests merged in 2018-10, with the labels that each got.

#255 Add tensorboard and check in vendor for the code search example.
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-code-search-trainer.jsonnet
  code_search/kubeflow/components/t2t-job.libsonnet
  code_search/kubeflow/components/tensorboard.jsonnet
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/parts.yaml
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/prototypes/tensorboard.jsonnet
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/prototypes/tf-batch-predict.jsonnet
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/prototypes/tf-job-simple-v1alpha1.jsonnet
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/prototypes/tf-job-simple.jsonnet
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/prototypes/tf-serving-simple.jsonnet
  code_search/kubeflow/vendor/kubeflow/examples@defc235463799d5600001ee0ed6ef68f7af24a17/prototypes/tf-serving-with-istio.jsonnet
Labels: approved, lgtm, size/XL

#252 add financial time series example
  README.md
  financial_time_series/.gitignore
  financial_time_series/Financial Time Series with Finance Data.ipynb
  financial_time_series/OWNERS
  financial_time_series/README.md
  financial_time_series/tensorflow_model/CPU/Dockerfile
  financial_time_series/tensorflow_model/CPU/train.jsonnet
  financial_time_series/tensorflow_model/Dockerfile
  financial_time_series/tensorflow_model/GPU/Dockerfile
  financial_time_series/tensorflow_model/GPU/train.jsonnet
  financial_time_series/tensorflow_model/__init__.py
  financial_time_series/tensorflow_model/metrics.py
  financial_time_series/tensorflow_model/models.py
  financial_time_series/tensorflow_model/preprocess.py
  financial_time_series/tensorflow_model/requirements.txt
  financial_time_series/tensorflow_model/run_train.py
  financial_time_series/tensorflow_model/serving_requests/__init__.py
  financial_time_series/tensorflow_model/serving_requests/request.py
  financial_time_series/tensorflow_model/serving_requests/request_helper.py
  financial_time_series/tensorflow_model/serving_requests/request_random.py
Labels: approved, lgtm, size/XXL

#264 Remove v1alpah1 TFJobs from the GH issue summarization example.
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/tensor2tensor.jsonnet
  github_issue_summarization/ks-kubeflow/components/tensor2tensor.libsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob-pvc.jsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob.jsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob.libsonnet
Labels: approved, lgtm, size/L

#267 minor fixes for instructions in README
  financial_time_series/README.md
Labels: approved, lgtm, size/S

#271 Fix bash
  object_detection/setup.md
Labels: approved, lgtm, size/XS

#276 Fix #275
  object_detection/ks-app/components/params.libsonnet
Labels: approved, lgtm, size/XS

#273 Fix #272
  object_detection/ks-app/components/create-pet-record-job.jsonnet
Labels: approved, lgtm, size/XS

#278 Upgrade demo to KF v0.3.1
  demos/yelp_demo/README.md
  demos/yelp_demo/demo/components/params.libsonnet
  demos/yelp_demo/demo/components/ui.libsonnet
  demos/yelp_demo/demo_setup/README.md
  demos/yelp_demo/demo_setup/kubeflow-demo-base.env
  demos/yelp_demo/notebooks/yelp.ipynb
Labels: approved, lgtm, size/L

#289 Create OWNERS file
  pipelines/OWNERS
Labels: approved, lgtm, size/XS
