Repository kubeflow/examples, pull requests merged in 2018-06, with the labels that each got.

#122 Fix utf-8 encoding issues in data pre-processing
  code_search/preprocess/preprocess/pipeline.py
  code_search/preprocess/preprocess/tokenizer.py
Labels: approved, lgtm, size/XS

#117 Proposed repo strategy
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/L

#125 Add num workers options to Dataflow
  code_search/.gitignore
  code_search/preprocess/README.md
  code_search/preprocess/files/select_github_archive.sql
  code_search/preprocess/preprocess/pipeline.py
  code_search/preprocess/scripts/process_github_archive.py
Labels: approved, lgtm, size/S

#127 New tensor2tensor problem datagen for function summarization
  code_search/README.md
  code_search/preprocess/README.md
  code_search/summarizer/gh_function_summarizer/__init__.py
  code_search/summarizer/gh_function_summarizer/function_summarizer.py
  code_search/summarizer/requirements.txt
Labels: approved, lgtm, size/L

#124 Tune application-focused description
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#128 Add error handling to Dataflow
  code_search/preprocess/MANIFEST.in
  code_search/preprocess/preprocess/pipeline.py
  code_search/preprocess/preprocess/tokenizer.py
  code_search/preprocess/scripts/process_github_archive.py
  code_search/preprocess/setup.py
Labels: approved, lgtm, size/L

#129 Language modeling using Transformer Networks
  code_search/README.md
  code_search/language_task/requirements.txt
  code_search/language_task/t2t_problems/__init__.py
  code_search/language_task/t2t_problems/docstring_lm.py
  code_search/language_task/t2t_problems/function_summarizer.py
Labels: approved, lgtm, size/M

#131 Isolate t2t execution into docker
  code_search/README.md
  code_search/language_task/Dockerfile
  code_search/language_task/build_image.sh
  code_search/language_task/requirements.txt
  code_search/language_task/run.sh
Labels: approved, lgtm, size/L

#130 Fixed distributed training for LINEAR model
  mnist/model.py
Labels: approved, lgtm, size/M

#141 Add custom metrics, write raw tokens to GCS
  code_search/preprocess/preprocess/pipeline.py
  code_search/preprocess/scripts/process_github_archive.py
Labels: approved, lgtm, size/M

#143 Language task on kubeflow
  code_search/README.md
  code_search/kubeflow/.gitignore
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-gh-summarizer.jsonnet
  code_search/kubeflow/components/t2t-job.libsonnet
  code_search/kubeflow/environments/base.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-job/README.md
  code_search/kubeflow/vendor/kubeflow/tf-job/parts.yaml
  code_search/kubeflow/vendor/kubeflow/tf-job/prototypes/tf-job.jsonnet
  code_search/kubeflow/vendor/kubeflow/tf-job/tf-job.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-job/util.libsonnet
  code_search/language_task/Dockerfile
  code_search/language_task/build_image.sh
  code_search/language_task/run.sh
  code_search/language_task/t2t-entrypoint.sh
Labels: approved, lgtm, size/XL

#150 Python package for indexing and serving the index
  code_search/indexing_server/Dockerfile
  code_search/indexing_server/build_image.sh
  code_search/indexing_server/nmslib_flask/__init__.py
  code_search/indexing_server/nmslib_flask/cli.py
  code_search/indexing_server/nmslib_flask/gcs.py
  code_search/indexing_server/nmslib_flask/search_engine.py
  code_search/indexing_server/nmslib_flask/search_server.py
  code_search/indexing_server/requirements.txt
  code_search/indexing_server/setup.py
Labels: approved, lgtm, size/L

#149 Extension of T2T Ksonnet component
  code_search/.gitignore
  code_search/README.md
  code_search/create_secrets.sh
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-job.libsonnet
  code_search/kubeflow/components/t2t-translate-datagen.jsonnet
  code_search/kubeflow/components/t2t-translate-exporter.jsonnet
  code_search/kubeflow/components/t2t-translate.jsonnet
  code_search/language_task/Dockerfile
  code_search/language_task/build_image.sh
Labels: approved, lgtm, size/L

#146 Add a new similarity transformer model, register new problem
  code_search/language_task/t2t_problems/docstring_lm.py
  code_search/language_task/t2t_problems/similarity_transformer.py
Labels: approved, lgtm, size/M

#155 Add component parameters
  github_issue_summarization/02_tensor2tensor_training.md
  github_issue_summarization/docker/flask_web/app.py
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/tensor2tensor.libsonnet
  github_issue_summarization/ks-kubeflow/components/ui.jsonnet
  github_issue_summarization/ks-kubeflow/components/ui.libsonnet
Labels: approved, lgtm, size/M

#157 Update the GH summarization example to Kubeflow 0.2 and TFJob v1alpha2.
  github_issue_summarization/ks-kubeflow/.gitignore
  github_issue_summarization/ks-kubeflow/.ksonnet/registries/kubeflow/20bdb46ee436b56fb9e3690d2a383b2afc8989f4.yaml
  github_issue_summarization/ks-kubeflow/.ksonnet/registries/kubeflow/3be196cfa1d68d9a33e0674c133ffbbcc3e57d46.yaml
  github_issue_summarization/ks-kubeflow/app.yaml
  github_issue_summarization/ks-kubeflow/components/kubeflow-core.jsonnet
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/tensor2tensor-v1alpha2.jsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob-v1alpha2.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/params.libsonnet
  github_issue_summarization/ks-kubeflow/tensor2tensor-v1alpha2.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/README.md
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/all.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/ambassador.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/centraldashboard.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/cert-manager.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/cloud-endpoints.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/configure_envoy_for_iap.sh
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/iap.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/jupyterhub.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/jupyterhub_spawner.py
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/kubeform_spawner.py
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/all.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/cert-manager.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/cloud-endpoints.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/iap-ingress.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/tensorboard.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/setup_iap.sh
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tensorboard.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/ambassador_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/centraldashboard_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/jupyterhub_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/nfs_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/spartakus_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/tf-job_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tf-job-operator.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/util.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/version-info.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/version.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/examples/parts.yaml
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/examples/prototypes/tensorboard.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/examples/prototypes/tf-job-simple-v1alpha1.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/examples/prototypes/tf-job-simple.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/examples/prototypes/tf-serving-simple.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/examples/prototypes/tf-serving-with-istio.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/prototypes/core.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/prototypes/serve-simple.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/serve-simple.libsonnet
Labels: approved, lgtm, size/XXL

#160 Fix model file upload
  github_issue_summarization/02_training_the_model_tfjob.md
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/notebooks/Makefile
  github_issue_summarization/notebooks/train.py
Labels: approved, lgtm, size/M
