Repository kubeflow/examples, pull requests merged in 2018-05, with the labels that each got.

#114 minst example - Add Azure instructions / update Argo package
  mnist/README.md
Labels: approved, lgtm, size/S

#115 Fix data-downloader; parameters are in the wrong order.
  github_issue_summarization/ks-kubeflow/components/data-downloader.jsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob.jsonnet
Labels: approved, lgtm, size/S

#116 Update README.md
  github_issue_summarization/README.md
Labels: approved, lgtm, size/XS

#120 Semantic Code Search Example Data Ingestion
  code_search/preprocess/.gitignore
  code_search/preprocess/MANIFEST.in
  code_search/preprocess/README.md
  code_search/preprocess/files/select_github_archive.sql
  code_search/preprocess/preprocess/__init__.py
  code_search/preprocess/preprocess/pipeline.py
  code_search/preprocess/preprocess/tokenizer.py
  code_search/preprocess/requirements.txt
  code_search/preprocess/scripts/process_github_archive.py
  code_search/preprocess/setup.py
Labels: approved, lgtm, size/L
