Repository kubeflow/examples, pull requests merged in 2018-11, with the labels that each got.

#294 Delete readme. Dir not necessary.
  pipelines/components/README.md
Labels: approved, lgtm, size/XS

#296 Remove inactive reviewers/approvers.
  OWNERS
Labels: approved, lgtm, size/XS

#306 [code search] add flag to wait till code search job finish
  code_search/src/code_search/dataflow/cli/arguments.py
  code_search/src/code_search/dataflow/cli/preprocess_github_dataset.py
Labels: approved, lgtm, size/XS

#307 [code search] update instruction with proper default namespace
  code_search/code-search.ipynb
Labels: approved, lgtm, size/XS

#302 Fix performance of dataflow preprocessing job.
  code_search/demo/cs-demo-1103/ks_app/components/params.libsonnet
  code_search/demo/cs-demo-1103/ks_app/environments/base.libsonnet
  code_search/demo/cs-demo-1103/ks_app/environments/default/globals.libsonnet
  code_search/demo/cs-demo-1103/ks_app/environments/default/main.jsonnet
  code_search/demo/cs-demo-1103/ks_app/environments/default/params.libsonnet
  code_search/docker/t2t/Dockerfile
  code_search/docker/t2t/build.sh
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/submit-preprocess-job.jsonnet
  code_search/src/code_search/dataflow/cli/arguments.py
  code_search/src/code_search/dataflow/cli/preprocess_github_dataset.py
  code_search/src/code_search/dataflow/cli/preprocess_github_dataset_test.py
  code_search/src/code_search/dataflow/cli/test_data/sample.json
  code_search/src/code_search/dataflow/do_fns/github_dataset.py
  code_search/src/code_search/dataflow/transforms/github_dataset.py
  code_search/src/code_search/dataflow/utils.py
Labels: approved, lgtm, size/XL

#311 [code search] Allow caller to wait until create function embedding job to finish
  code_search/src/code_search/dataflow/cli/create_function_embeddings.py
Labels: approved, lgtm, size/XS

#317 code search example make distributed training work; Create some components to train models
  code_search/.gitignore
  code_search/Makefile
  code_search/demo/README.md
  code_search/docker/t2t/Dockerfile
  code_search/docker/t2t/Dockerfile.dataflow
  code_search/docker/t2t/README.md
  code_search/docker/t2t/build.jsonnet
  code_search/docker/t2t/build.sh
  code_search/docker/t2t/run_and_wait.sh
  code_search/docker/t2t/t2t-entrypoint.sh
  code_search/kubeflow/components/demo-tensorboard.jsonnet
  code_search/kubeflow/components/demo-trainer-11-05-dist-sync-gpu.jsonnet
  code_search/kubeflow/components/demo-trainer-11-05-single-gpu.jsonnet
  code_search/kubeflow/components/demo-trainer-11-05-tinyparams.jsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-job.libsonnet
  code_search/kubeflow/environments/cs_demo/globals.libsonnet
  code_search/kubeflow/environments/cs_demo/main.jsonnet
  code_search/kubeflow/environments/cs_demo/params.libsonnet
  code_search/src/code_search/t2t/similarity_transformer.py
  code_search/src/code_search/t2t/start_std_server.py
Labels: approved, lgtm, size/XL

#330 Change dataflow default workdir to /src
  code_search/docker/t2t/Dockerfile.dataflow
Labels: approved, lgtm, size/XS

#320 Modify K8s models to export the models; tensorboard manifests
  code_search/docker/t2t/Dockerfile
  code_search/kubeflow/components/demo-export-11-05-dist-sync-gpu.jsonnet
  code_search/kubeflow/components/demo-tensorboard.jsonnet
  code_search/kubeflow/components/demo-trainer-11-05-dist-sync-gpu.jsonnet
  code_search/kubeflow/components/demo-trainer-11-05-single-gpu.jsonnet
  code_search/kubeflow/components/demo-trainer-11-05-tinyparams.jsonnet
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/export-model.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-code-search-exporter.jsonnet
  code_search/kubeflow/components/t2t-job.libsonnet
  code_search/kubeflow/environments/cs_demo/globals.libsonnet
  code_search/kubeflow/environments/cs_demo/main.jsonnet
  code_search/kubeflow/environments/cs_demo/params.libsonnet
Labels: approved, lgtm, size/L

#327 Early termination if t2t job failed
  code_search/docker/t2t/run_and_wait.sh
  code_search/docker/t2t/t2t-entrypoint.sh
Labels: approved, lgtm, size/XS

#324 Create a component to submit the Dataflow job to compute embeddings for code search
  code_search/Makefile
  code_search/docker/t2t/Dockerfile.dataflow
  code_search/docker/t2t/build.jsonnet
  code_search/kubeflow/README.md
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/submit-code-embeddings-job.jsonnet
  code_search/kubeflow/components/submit-code-embeddings-job.libsonnet
  code_search/kubeflow/components/submit-preprocess-job.jsonnet
  code_search/kubeflow/environments/cs_demo/globals.libsonnet
  code_search/src/code_search/dataflow/cli/create_function_embeddings.py
  code_search/src/requirements.dataflow.txt
  code_search/src/requirements.ui.txt
  code_search/src/setup.py
Labels: approved, lgtm, size/L

#333 Remove ksonnet registry from dockerignore file
  code_search/.dockerignore
Labels: approved, lgtm, size/XS

#322 Simple pipeline demo
  demos/simple_pipeline/README.md
  demos/simple_pipeline/demo_setup/README.md
  demos/simple_pipeline/gpu-example-katib.yaml
  demos/simple_pipeline/gpu-example-pipeline.py
  demos/simple_pipeline/gpu-example-pipeline.yaml
  demos/simple_pipeline/kubeflow-demo-base.env
  demos/simple_pipeline/kubeflow-demo-simple-pipeline.env
Labels: approved, lgtm, size/XL

#338 Fix the K8s job to create the nmslib index.
  code_search/Makefile
  code_search/demo/cs-demo-1103/gcp_config/cluster-kubeflow.yaml
  code_search/demo/cs-demo-1103/gcp_config/cluster.jinja
  code_search/docker/t2t/Dockerfile.dataflow
  code_search/docker/t2t/build.jsonnet
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/nms.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/search-index-creator.jsonnet
  code_search/kubeflow/components/tensorboard.jsonnet
  code_search/src/code_search/nmslib/cli/create_search_index.py
  code_search/src/code_search/nmslib/cli/start_search_server.py
  code_search/src/requirements.nmslib.txt
Labels: approved, lgtm, size/L

#354 Fix the ksonnet by defining globals.
  code_search/kubeflow/components/params.libsonnet
Labels: approved, lgtm, size/XS

#356 add pipeline component
  code_search/demo/cs-demo-1103/ks_app/app.yaml
  code_search/demo/cs-demo-1103/ks_app/components/params.libsonnet
  code_search/demo/cs-demo-1103/ks_app/components/pipeline.jsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/OWNERS
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/all.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/minio.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/mysql.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/parts.yaml
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/pipeline-apiserver.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/pipeline-persistenceagent.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/pipeline-scheduledworkflow.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/pipeline-ui.libsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/prototypes/pipeline.jsonnet
  code_search/demo/cs-demo-1103/ks_app/vendor/kfp/pipeline@af3376fee4229507acc3a5f3af8b129c9a48a2dc/spartakus.libsonnet
Labels: approved, lgtm, size/XXL

#352 Create a script to update the index and lookup file used to serve predictions
  code_search/Makefile
  code_search/docker/index_updater/Dockerfile
  code_search/docker/index_updater/README.md
  code_search/docker/index_updater/build.jsonnet
  code_search/docker/index_updater/update_index.sh
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/search-index-server.jsonnet
  code_search/kubeflow/environments/cs_demo/params.libsonnet
Labels: approved, lgtm, size/L

#358 parameterize search index job name
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/search-index-creator.jsonnet
  code_search/kubeflow/environments/pipeline/globals.libsonnet
  code_search/kubeflow/environments/pipeline/main.jsonnet
  code_search/kubeflow/environments/pipeline/params.libsonnet
Labels: approved, lgtm, size/M

#359 Setup ArgoCD to synchornize the code search web app with the demo cluster
  code_search/README.md
  code_search/code-search.ipynb
  code_search/demo/README.md
  code_search/demo/cs-demo-1103/k8s_specs/argo_cd.yaml
  code_search/demo/cs-demo-1103/web-app-argocd-app.yaml
  code_search/ks-web-app/.gitignore
  code_search/ks-web-app/app.yaml
  code_search/ks-web-app/components/params.libsonnet
  code_search/ks-web-app/components/query-embed-server.jsonnet
  code_search/ks-web-app/components/search-index-server.jsonnet
  code_search/ks-web-app/environments/base.libsonnet
  code_search/ks-web-app/environments/cs_demo/globals.libsonnet
  code_search/ks-web-app/environments/cs_demo/main.jsonnet
  code_search/ks-web-app/environments/cs_demo/params.libsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/README.md
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/parts.yaml
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/prototypes/tf-serving-all-features.jsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/prototypes/tf-serving-aws.jsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/prototypes/tf-serving-gcp.jsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/prototypes/tf-serving-with-request-log.jsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/tf-serving-template.libsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/tf-serving.libsonnet
  code_search/ks-web-app/vendor/kubeflow/tf-serving@dddba26893846041b7cee25ee6121e02a04bd503/util.libsonnet
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
Labels: approved, lgtm, size/XXL

#347 Add ks env configuration(#346)
  object_detection/ks-app/app.yaml
  object_detection/ks-app/environments/base.libsonnet
  object_detection/setup.md
Labels: approved, lgtm, ok-to-test, size/S

#361 Add update search index pipeline
  code_search/Makefile
  code_search/docker/index_updater/Dockerfile
  code_search/docker/index_updater/README.md
  code_search/docker/ks/Dockerfile
  code_search/docker/ks/build.jsonnet
  code_search/docker/ks/launch_search_index_creator_job.sh
  code_search/docker/ks/parse_arguments.sh
  code_search/docker/ks/update_index.sh
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/pipeline/README.md
  code_search/pipeline/index_update_pipeline.py
Labels: approved, lgtm, size/L

#371 Update setup.py to point to the new requirement file
  code_search/src/setup.py
Labels: approved, lgtm, size/XS

#370 Cleanup build directory before code search GCB build
  code_search/Makefile
Labels: approved, lgtm, size/XS

#369 Highlight the kubectl command.
  object_detection/setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#360 [pytorch_mnist] Point images back to gcr.io/kubeflow-examples
  pytorch_mnist/ks_app/components/params.libsonnet
  pytorch_mnist/serving/seldon-wrapper/build_image.sh
  pytorch_mnist/training/ddp/mnist/cpu/v1alpha2/job_mnist_DDP_CPU.yaml
  pytorch_mnist/training/ddp/mnist/gpu/v1alpha2/job_mnist_DDP_GPU.yaml
Labels: approved, lgtm, size/S

#367 tf-training-job doesn't complete
  object_detection/docker/Dockerfile.training
  object_detection/ks-app/components/get-data-job.jsonnet
  object_detection/ks-app/components/tf-training-job.jsonnet
Labels: approved, lgtm, ok-to-test, size/S

#373 Update the update_index.sh
  code_search/docker/ks/Dockerfile
  code_search/docker/ks/update_index.sh
  code_search/pipeline/README.md
Labels: approved, lgtm, size/M

#372 add pipeline environment to code search web app
  code_search/ks-web-app/app.yaml
  code_search/ks-web-app/environments/pipeline/globals.libsonnet
  code_search/ks-web-app/environments/pipeline/main.jsonnet
  code_search/ks-web-app/environments/pipeline/params.libsonnet
Labels: approved, lgtm, size/M
