Repository kubeflow/examples, pull requests merged in 2018-12, with the labels that each got.

#386 Add IronPan to code_search owner
  code_search/OWNERS
Labels: approved, lgtm, size/XS

#387 add pipeline step to push to git
  code_search/docker/ks/launch_search_index_creator_job.sh
  code_search/docker/ks/submit_code_embeddings_job.sh
  code_search/docker/ks/update_index.sh
  code_search/pipeline/index_update_pipeline.py
Labels: approved, lgtm, size/L

#388 Dataflow job should support writing embeddings to a different location (Fix #366).
  code_search/docker/t2t/Dockerfile.dataflow
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/submit-code-embeddings-job.libsonnet
  code_search/src/code_search/dataflow/cli/arguments.py
  code_search/src/code_search/dataflow/cli/create_function_embeddings.py
  code_search/src/code_search/dataflow/transforms/bigquery.py
  code_search/src/code_search/dataflow/transforms/function_embeddings.py
  code_search/src/code_search/dataflow/transforms/github_bigquery.py
  code_search/src/setup.py
Labels: approved, lgtm, size/L

#394 Update the ks parameter
  code_search/docker/ks/launch_search_index_creator_job.sh
  code_search/docker/ks/submit_code_embeddings_job.sh
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/search-index-creator.jsonnet
  code_search/kubeflow/components/submit-code-embeddings-job.libsonnet
  code_search/pipeline/index_update_pipeline.py
Labels: approved, lgtm, size/M

#402 Replace files that were mistakenly removed in #376
  demos/yelp_demo/ks_app/components/serving.jsonnet
  demos/yelp_demo/ks_app/components/t2tcpu.jsonnet
  demos/yelp_demo/ks_app/components/t2tgpu.jsonnet
  demos/yelp_demo/ks_app/components/t2ttpu.jsonnet
  demos/yelp_demo/ks_app/components/ui.jsonnet
  demos/yelp_demo/ks_app/components/ui.libsonnet
Labels: approved, lgtm, size/XL

#396 Add preprocess github data step to code search pipeline
  code_search/docker/ks/launch_search_index_creator_job.sh
  code_search/docker/ks/submit_code_embeddings_job.sh
  code_search/docker/ks/update_index.sh
  code_search/kubeflow/components/experiments.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/search-index-creator.jsonnet
  code_search/kubeflow/components/submit-code-embeddings-job.libsonnet
  code_search/kubeflow/components/submit-preprocess-job.jsonnet
  code_search/pipeline/index_update_pipeline.py
  code_search/src/code_search/dataflow/cli/arguments.py
  code_search/src/code_search/dataflow/cli/create_function_embeddings.py
  code_search/src/code_search/dataflow/cli/preprocess_github_dataset.py
  code_search/src/code_search/dataflow/transforms/bigquery.py
  code_search/src/code_search/dataflow/transforms/github_bigquery.py
  code_search/src/code_search/dataflow/transforms/github_dataset.py
Labels: approved, lgtm, size/L

#403 Fixing broken links
  github_issue_summarization/01_setup_a_kubeflow_cluster.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#378 add object detection grpc client
  .pylintrc
  object_detection/serving_script/object_detection_grpc_client.py
  object_detection/tf_serving_cpu.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#406 Clean up code search pipeline
  code_search/pipeline/index_update_pipeline.py
Labels: approved, lgtm, size/M

#413 Expose ArgoCD UI behind Ambassador.
  code_search/demo/cs-demo-1103/k8s_specs/argo_cd.yaml
  code_search/demo/cs-demo-1103/k8s_specs/argo_cd_ui_mapping.yaml
Labels: approved, lgtm, size/M

#409 reconcile tensorflow serving version
  object_detection/docker/Dockerfile.training
  object_detection/ks-app/components/params.libsonnet
Labels: approved, lgtm, ok-to-test, size/XS

#415 Fix curl command when sending request to seldon-served model on GKE
  xgboost_ames_housing/README.md
Labels: approved, lgtm, ok-to-test, size/S

#416 Fix directories in Dockerfile
  xgboost_ames_housing/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#419 Add pods/logs permission to the jupyter notebook role.
  code_search/demo/cs-demo-1103/ks_app/vendor/kubeflow/core/jupyterhub.libsonnet
Labels: approved, lgtm, size/XS

#421 Point images back to gcr.io/kubeflow-examples
  prow_config.yaml
Labels: approved, lgtm, size/S

#418 fix bq table dupliation
  code_search/pipeline/CodeSearchPipelineNotebook.ipynb
  code_search/pipeline/index_update_pipeline.py
Labels: approved, lgtm, size/M

#432 Fix the web app.
  code_search/demo/README.md
  code_search/ks-web-app/environments/cs_demo/params.libsonnet
Labels: approved, lgtm, size/M

#430 Update the central dashboard UI image to one that includes pipelines.
  code_search/demo/cs-demo-1103/ks_app/components/params.libsonnet
Labels: approved, lgtm, size/XS

#407 remove obsolete PS in GPU jsonnet
  financial_time_series/tensorflow_model/GPU/train.jsonnet
Labels: approved, lgtm, needs-ok-to-test, size/S

#375 Removed empty application centric section.
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#379 Create a script to count lines of code.
  code_search/demo/count_lines_of_code.py
Labels: approved, lgtm, size/L

#439 create pv for pets-pv
  object_detection/setup.md
Labels: approved, lgtm, size/S

#444 Pushing web-ui and model serve images to gcr.io/kubeflow-examples
  pytorch_mnist/serving/seldon-wrapper/mnistddpserving.py
  pytorch_mnist/web-ui/mnist_client.py
Labels: approved, lgtm, size/XS

#446 An Argo workflow to use as the E2E test for code_search example.
  code_search/Makefile
  code_search/developer_guide.md
  code_search/docker/t2t/Dockerfile
  code_search/docker/t2t/build.jsonnet
  prow_config.yaml
  test/workflows/app.yaml
  test/workflows/components/code_search.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/util.libsonnet
  test/workflows/environments/test/.metadata/k.libsonnet
  test/workflows/environments/test/.metadata/k8s.libsonnet
  test/workflows/environments/test/.metadata/swagger.json
  test/workflows/environments/test/globals.libsonnet
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/ksonnet-lib/v1.10.9/k.libsonnet
  test/workflows/lib/ksonnet-lib/v1.10.9/k8s.libsonnet
  test/workflows/lib/ksonnet-lib/v1.10.9/swagger.json
Labels: approved, lgtm, size/XXL

#447 Fix example documentation
  financial_time_series/README.md
Labels: approved, lgtm, size/XS

#451 Delete obsolete HP tuning code.
  github_issue_summarization/hp-tune/Dockerfile
  github_issue_summarization/hp-tune/Gopkg.lock
  github_issue_summarization/hp-tune/Gopkg.toml
  github_issue_summarization/hp-tune/Makefile
  github_issue_summarization/hp-tune/README.md
  github_issue_summarization/hp-tune/git-issue-summarize-demo.go
Labels: approved, lgtm, size/XL
