Repository kubeflow/examples, pull requests merged in 2018-08, with the labels that each got.

#205 Fix T2T memory problem
  code_search/src/code_search/dataflow/cli/create_function_embeddings.py
  code_search/src/code_search/dataflow/cli/preprocess_github_dataset.py
  code_search/src/code_search/t2t/function_docstring.py
  code_search/src/code_search/t2t/similarity_transformer.py
Labels: approved, lgtm, size/L

#192 Parametrize Object detection example
  object_detection/export_tf_graph.md
  object_detection/jobs/00create-pvc.yaml
  object_detection/jobs/01get-dataset.yaml
  object_detection/jobs/02get-annotations.yaml
  object_detection/jobs/03get-model-job.yaml
  object_detection/jobs/04decompress-images.yaml
  object_detection/jobs/05decompress-annotations.yaml
  object_detection/jobs/06decompress-model.yaml
  object_detection/jobs/07get-fasterrcnn-config.yaml
  object_detection/jobs/08create-pet-record.yaml
  object_detection/jobs/export-tf-graph.yaml
  object_detection/jobs/pets-training.yaml
  object_detection/ks-app/components/create-pet-record-job.jsonnet
  object_detection/ks-app/components/decompress-data-job.jsonnet
  object_detection/ks-app/components/export-tf-graph-job.jsonnet
  object_detection/ks-app/components/get-data-job.jsonnet
  object_detection/ks-app/components/params.libsonnet
  object_detection/ks-app/components/pets-model.jsonnet
  object_detection/ks-app/components/pets-pvc.jsonnet
  object_detection/ks-app/components/tf-training-job.jsonnet
  object_detection/monitor_job.md
  object_detection/setup.md
  object_detection/submit_job.md
  object_detection/tf_serving_cpu.md
Labels: approved, lgtm, size/XL

#207 Disable Distributed Training
  code_search/README.md
  code_search/create_secrets.sh
  code_search/docker/t2t/build.sh
  code_search/docker/t2t/t2t-entrypoint.sh
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-code-search-datagen.jsonnet
  code_search/kubeflow/components/t2t-job.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-job/README.md
  code_search/kubeflow/vendor/kubeflow/tf-job/parts.yaml
  code_search/kubeflow/vendor/kubeflow/tf-job/prototypes/tf-job.jsonnet
  code_search/kubeflow/vendor/kubeflow/tf-job/tf-job.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-job/util.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@e95f94a1a97a0974ada734895d590b5ba565fa77/README.md
  code_search/kubeflow/vendor/kubeflow/tf-serving@e95f94a1a97a0974ada734895d590b5ba565fa77/parts.yaml
  code_search/kubeflow/vendor/kubeflow/tf-serving@e95f94a1a97a0974ada734895d590b5ba565fa77/prototypes/tf-serving-all-features.jsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@e95f94a1a97a0974ada734895d590b5ba565fa77/tf-serving.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@e95f94a1a97a0974ada734895d590b5ba565fa77/util.libsonnet
Labels: approved, lgtm, size/XL

#199 Batch predict example for object detection using GPU
  object_detection/README.md
  object_detection/batch-predict/batch-predict.yaml
  object_detection/docker/Dockerfile.batch-predict
  object_detection/docker/Dockerfile.training
  object_detection/submit_batch_predict.md
  object_detection/submit_job.md
Labels: approved, lgtm, size/L

#209 Merge UI and Search Server
  code_search/docker/ui/Dockerfile
  code_search/src/code_search/nmslib/cli.py
  code_search/src/code_search/nmslib/cli/__init__.py
  code_search/src/code_search/nmslib/cli/arguments.py
  code_search/src/code_search/nmslib/cli/create_search_index.py
  code_search/src/code_search/nmslib/cli/start_search_server.py
  code_search/src/code_search/nmslib/gcs.py
  code_search/src/code_search/nmslib/search_engine.py
  code_search/src/code_search/nmslib/search_server.py
  code_search/src/requirements.txt
  code_search/src/setup.py
  code_search/src/ui/.gitignore
  code_search/src/ui/package-lock.json
  code_search/src/ui/package.json
  code_search/src/ui/public/favicon.ico
  code_search/src/ui/public/index.html
  code_search/src/ui/public/manifest.json
  code_search/src/ui/src/App.css
  code_search/src/ui/src/App.js
  code_search/src/ui/src/App.test.js
  code_search/src/ui/src/CodeSample.js
  code_search/src/ui/src/CodeSearchApi.js
  code_search/src/ui/src/index.css
  code_search/src/ui/src/index.js
  code_search/src/ui/src/logo.svg
  code_search/src/ui/src/registerServiceWorker.js
  code_search/src/ui/src/theme.js
  code_search/ui/README.md
Labels: approved, lgtm, size/XXL

#211 Fixed broken links in object detection example
  object_detection/export_tf_graph.md
  object_detection/submit_job.md
  object_detection/tf_serving_cpu.md
Labels: approved, lgtm, size/XS

#214 Create Jupyter notebook image for codelabs
  codelab-image/Dockerfile
  codelab-image/Makefile
  codelab-image/README.md
Labels: approved, lgtm, size/M

#216 Update Ksonnet version, Add Python2 pip
  codelab-image/Dockerfile
  codelab-image/README.md
Labels: approved, lgtm, size/S

#213 Update Search Index server spec
  code_search/docker/t2t/build.sh
  code_search/docker/ui/Dockerfile
  code_search/docker/ui/build.sh
  code_search/kubeflow/components/nms.libsonnet
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/search-index-creator.jsonnet
  code_search/kubeflow/components/search-index-server.jsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@e95f94a1a97a0974ada734895d590b5ba565fa77/tf-serving.libsonnet
  code_search/src/code_search/nmslib/search_server.py
  code_search/src/ui/src/CodeSearchApi.js
Labels: approved, lgtm, size/L

#217 Add a Jupyter notebook to be used for Kubeflow codelabs
  code_search/README.md
  code_search/code-search.ipynb
Labels: approved, lgtm, size/XL

#221 Small fix to TF serving gpu
  object_detection/tf_serving_gpu.md
Labels: approved, lgtm, size/XS

#224 Allow ks param set for Code Search Ksonnet Application
  code_search/code-search.ipynb
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/components/t2t-code-search.jsonnet
Labels: approved, lgtm, size/L

#225 Add a new github function docstring extended problem
  code_search/kubeflow/components/params.libsonnet
  code_search/src/code_search/t2t/__init__.py
  code_search/src/code_search/t2t/function_docstring.py
  code_search/src/code_search/t2t/function_docstring_extended.py
Labels: approved, lgtm, size/M

#229 Upgrade notebook commands and other relevant changes
  code_search/README.md
  code_search/code-search.ipynb
  code_search/docker/t2t/Dockerfile
  code_search/docker/ui/Dockerfile
  code_search/kubeflow/app.yaml
  code_search/kubeflow/components/params.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@ab6084349673e6405ae486eb3be2141e3550643c/README.md
  code_search/kubeflow/vendor/kubeflow/tf-serving@ab6084349673e6405ae486eb3be2141e3550643c/parts.yaml
  code_search/kubeflow/vendor/kubeflow/tf-serving@ab6084349673e6405ae486eb3be2141e3550643c/prototypes/tf-serving-all-features.jsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@ab6084349673e6405ae486eb3be2141e3550643c/prototypes/tf-serving-with-request-log.jsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@ab6084349673e6405ae486eb3be2141e3550643c/tf-serving.libsonnet
  code_search/kubeflow/vendor/kubeflow/tf-serving@ab6084349673e6405ae486eb3be2141e3550643c/util.libsonnet
  code_search/src/code_search/nmslib/cli/create_search_index.py
  code_search/src/code_search/t2t/function_docstring.py
  code_search/src/code_search/t2t/function_docstring_extended.py
  code_search/src/code_search/t2t/similarity_transformer.py
  code_search/src/requirements.txt
Labels: approved, lgtm, size/XL

#228 Updated object detection training example
  object_detection/conf/faster_rcnn_resnet101_pets.config
  object_detection/docker/Dockerfile.training
  object_detection/export_tf_graph.md
  object_detection/ks-app/components/export-tf-graph-job.jsonnet
  object_detection/ks-app/components/params.libsonnet
  object_detection/ks-app/components/tf-training-job.jsonnet
  object_detection/monitor_job.md
  object_detection/setup.md
Labels: approved, lgtm, size/L

#232 new PR for XGBoost due to problems with history rewrite
  xgboost_ames_housing/Dockerfile
  xgboost_ames_housing/README.md
  xgboost_ames_housing/housing.py
  xgboost_ames_housing/py-claim.yaml
  xgboost_ames_housing/py-pod.yaml
  xgboost_ames_housing/py-volume.yaml
  xgboost_ames_housing/seldon_serve/HousingServe.py
  xgboost_ames_housing/seldon_serve/housing.dat
  xgboost_ames_housing/seldon_serve/requirements.txt
Labels: approved, lgtm, size/L

#236 Update README.md
  README.md
Labels: size/S

#203 Add estimator example for github issues
  .gitignore
  github_issue_summarization/02_distributed_training.md
  github_issue_summarization/02_tensor2tensor_training.md
  github_issue_summarization/README.md
  github_issue_summarization/distributed/Dockerfile
  github_issue_summarization/distributed/storage.yaml
  github_issue_summarization/distributed/tfjob.yaml
  github_issue_summarization/distributed/train.py
  github_issue_summarization/tensor2tensor/github/Dockerfile
  github_issue_summarization/tensor2tensor/github/Makefile
  github_issue_summarization/tensor2tensor/github/__init__.py
  github_issue_summarization/tensor2tensor/github/github_problem.py
  github_issue_summarization/tensor2tensor/github/t2t_launcher.sh
Labels: approved, lgtm, size/XL

#235 Fixed broken link in github issue summarization example
  github_issue_summarization/02_training_the_model.md
Labels: approved, lgtm, size/XS
