Repository kubeflow/examples, pull requests merged in 2018-09, with the labels that each got.

#246 example mnist upgrade to v1alpha2
  mnist/README.md
  mnist/model-train.yaml
Labels: approved, lgtm, size/L

#248 Update demo script & add notebook
  demos/yelp_demo/README.md
  demos/yelp_demo/demo_setup/README.md
  demos/yelp_demo/demo_setup/kubeflow-demo-base.env
  demos/yelp_demo/notebooks/README.md
  demos/yelp_demo/notebooks/noise.png
  demos/yelp_demo/notebooks/semantics.png
  demos/yelp_demo/notebooks/signal.png
  demos/yelp_demo/notebooks/yelp.ipynb
Labels: approved, lgtm, size/XXL

#240 [GH Issue Summarization] Add setup steps
  github_issue_summarization/01_setup_a_kubeflow_cluster.md
Labels: approved, lgtm, size/S

#253 Ankush Signing Out
  OWNERS
Labels: approved, lgtm, size/XS
