Repository kubeflow/examples, pull requests merged in 2018-04, with the labels that each got.

#57 Add namespace to ksonnet apply command
  .pylintrc
  github_issue_summarization/docker/flask_web/templates/issue_summary.html
  github_issue_summarization/docker/flask_web/templates/summary.html
  github_issue_summarization/querying_the_model.md
Labels: approved, lgtm, size/S

#42 Fixes #2: End to end model training/serving example using S3, Argo, and Kubeflow
  README.md
  mnist/Dockerfile.ksonnet
  mnist/Dockerfile.model
  mnist/README.md
  mnist/data/0.png
  mnist/data/1.png
  mnist/data/2.png
  mnist/data/3.png
  mnist/data/4.png
  mnist/data/5.png
  mnist/data/6.png
  mnist/data/7.png
  mnist/data/8.png
  mnist/data/9.png
  mnist/ksonnet-entrypoint.sh
  mnist/mnist_client.py
  mnist/model-deploy.yaml
  mnist/model-train.yaml
  mnist/model.py
  mnist/requirements.txt
  mnist/tf-user.yaml
Labels: approved, lgtm, size/XXL

#72 Restore runnability of example; vendor agnostic storage
  agents/README.md
  agents/app/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  agents/app/.ksonnet/registries/kubeflow/8b48d28127cb719410a9c40be214d3c76c2b4cb7.yaml
  agents/app/app.yaml
  agents/app/components/params.libsonnet
  agents/app/components/render.jsonnet
  agents/app/components/tensorboard.jsonnet
  agents/app/components/tensorboard.libsonnet
  agents/app/components/train.jsonnet
  agents/app/lib/v1.7.0/k.libsonnet
  agents/app/lib/v1.7.0/k8s.libsonnet
  agents/app/lib/v1.7.0/swagger.json
  agents/app/vendor/kubeflow/tf-job/README.md
  agents/app/vendor/kubeflow/tf-job/parts.yaml
  agents/app/vendor/kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
  agents/app/vendor/kubeflow/tf-job/prototypes/tf-job.jsonnet
  agents/app/vendor/kubeflow/tf-job/tf-job.libsonnet
  agents/doc/demo.ipynb
  agents/tools/builder/Dockerfile
  agents/tools/builder/README.md
  agents/tools/builder/builder.yaml
  agents/tools/release/envless_commit.sh
  agents/tools/release/release_demo_container.sh
  agents/trainer/task.py
Labels: approved, lgtm, size/XXL

#68 Rename issue_summarization.py to IssueSummarization.py
  github_issue_summarization/notebooks/IssueSummarization.py
Labels: approved, lgtm, size/XS

#69 Polish the github issue summarization UI
  github_issue_summarization/docker/Dockerfile
  github_issue_summarization/docker/flask_web/app.py
  github_issue_summarization/docker/flask_web/requirements.txt
  github_issue_summarization/docker/flask_web/templates/index.html
  github_issue_summarization/docker/flask_web/templates/issue_summary.html
Labels: approved, lgtm, size/L

#71 Use ambassador to talk to the frontend ui
  github_issue_summarization/notebooks/Dockerfile
  github_issue_summarization/notebooks/ks-app/.ksonnet/registries/incubator/40285d8a14f1ac5787e405e1023cf0c07f6aa28c.yaml
  github_issue_summarization/notebooks/ks-app/app.yaml
  github_issue_summarization/notebooks/ks-app/components/params.libsonnet
  github_issue_summarization/notebooks/ks-app/components/tfjob.jsonnet
  github_issue_summarization/notebooks/ks-app/components/tfjob.libsonnet
  github_issue_summarization/notebooks/ks-app/components/ui.jsonnet
  github_issue_summarization/notebooks/ks-app/components/ui.libsonnet
  github_issue_summarization/notebooks/ks-app/environments/base.libsonnet
  github_issue_summarization/notebooks/ks-app/environments/default/main.jsonnet
  github_issue_summarization/notebooks/ks-app/environments/default/params.libsonnet
  github_issue_summarization/notebooks/ks-app/lib/v1.7.0/k.libsonnet
  github_issue_summarization/notebooks/ks-app/lib/v1.7.0/k8s.libsonnet
  github_issue_summarization/notebooks/ks-app/lib/v1.7.0/swagger.json
  github_issue_summarization/notebooks/train.py
  github_issue_summarization/querying_the_model.md
  github_issue_summarization/training_the_model_tfjob.md
Labels: approved, lgtm, size/L

#80 Fix IssueSummarization.py typo
  github_issue_summarization/serving_the_model.md
Labels: approved, lgtm, size/XS

#83 Removing uneeded requirements, this was causing pip errors.
  mnist/requirements.txt
Labels: approved, lgtm, size/S

#85 Issue summarization UI sends request to model service directly
  github_issue_summarization/docker/flask_web/app.py
Labels: approved, lgtm, size/XS

#86 Distributed training using tensor2tensor
  github_issue_summarization/README.md
  github_issue_summarization/notebooks/ks-app/components/params.libsonnet
  github_issue_summarization/notebooks/ks-app/components/tensor2tensor.jsonnet
  github_issue_summarization/notebooks/ks-app/components/tensor2tensor.libsonnet
  github_issue_summarization/tensor2tensor/github/Dockerfile
  github_issue_summarization/tensor2tensor/github/__init__.py
  github_issue_summarization/tensor2tensor/github/github_problem.py
  github_issue_summarization/tensor2tensor/github/ps_dist_launcher.sh
  github_issue_summarization/tensor2tensor/github/train_dist_launcher.sh
  github_issue_summarization/tensor2tensor_training.md
Labels: approved, lgtm, size/L

#95 Fix failing test due to https://github.com/kubeflow/testing/pull/111
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#94 Remove vendor from .gitignore
  .gitignore
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/README.md
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/all.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/ambassador.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/cert-manager.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/iap.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/jupyterhub.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/jupyterhub_spawner.py
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/nfs.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/parts.yaml
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/all.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/cert-manager.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/iap-ingress.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/spartakus.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/ambassador_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/iap_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/jupyterhub_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/nfs_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/spartakus_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/tf-job_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/util_test.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tf-job.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/util.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/core.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/crd.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/apife-deployment.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/apife-service.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/operator-deployment.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/pod-template-spec-validation.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/rbac-cluster-binding.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/rbac-service-account.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/redis-deployment.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/json/redis-service.json
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/parts.yaml
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/prototypes/core.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/prototypes/serve-simple.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/seldon/serve-simple.libsonnet
Labels: approved, lgtm, size/XXL

#97 Add a job to download the data to PVC.
  github_issue_summarization/ks-kubeflow/components/data-downloader.jsonnet
  github_issue_summarization/ks-kubeflow/components/data-pvc.jsonnet
  github_issue_summarization/ks-kubeflow/components/download_data.sh
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
Labels: approved, lgtm, size/L

#98 Support training using a PVC for the data.
  github_issue_summarization/ks-kubeflow/app.yaml
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob-pvc.jsonnet
  github_issue_summarization/ks-kubeflow/components/tfjob.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/params.libsonnet
  github_issue_summarization/notebooks/Dockerfile
  github_issue_summarization/notebooks/Makefile
  github_issue_summarization/notebooks/train.py
  github_issue_summarization/training_the_model_tfjob.md
Labels: approved, lgtm, size/L

#99 Replace kubeflow-images-staging with kubeflow-images-public
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/ui.libsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/jupyterhub_spawner.py
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/all.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/prototypes/iap-ingress.jsonnet
  github_issue_summarization/ks-kubeflow/vendor/kubeflow/core/tests/tf-job_test.jsonnet
  github_issue_summarization/notebooks/Dockerfile
  github_issue_summarization/tensor2tensor/github/Dockerfile
Labels: approved, lgtm, size/M

#107 Make it easier to demo serving and run in Katacoda
  .gitignore
  github_issue_summarization/ks-kubeflow/app.yaml
  github_issue_summarization/ks-kubeflow/components/data-downloader.jsonnet
  github_issue_summarization/ks-kubeflow/components/download_data.sh
  github_issue_summarization/ks-kubeflow/components/issue-summarization-model-serving.jsonnet
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/kubecon-gh-demo-1/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/kubecon-gh-demo-1/params.libsonnet
  github_issue_summarization/notebooks/IssueSummarization.py
  github_issue_summarization/notebooks/Makefile
  github_issue_summarization/serving_the_model.md
Labels: approved, lgtm, size/L

#110 Add a component to run TensorBoard.
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/tensorboard.jsonnet
Labels: approved, lgtm, size/M

#109 Improvements to the tensor2tensor trainer for the GitHub summarization example.
  github_issue_summarization/ks-kubeflow/components/params.libsonnet
  github_issue_summarization/ks-kubeflow/components/tensor2tensor.jsonnet
  github_issue_summarization/ks-kubeflow/components/tensor2tensor.libsonnet
  github_issue_summarization/tensor2tensor/github/Dockerfile
  github_issue_summarization/tensor2tensor/github/Makefile
  github_issue_summarization/tensor2tensor/github/ps_dist_launcher.sh
  github_issue_summarization/tensor2tensor/github/t2t_launcher.sh
  github_issue_summarization/tensor2tensor/github/train_dist_launcher.sh
Labels: approved, lgtm, size/L

#108 Updating mnist example to fix minio compatibility
  mnist/Dockerfile.ksonnet
  mnist/Dockerfile.model
  mnist/README.md
  mnist/ksonnet-entrypoint.sh
  mnist/model-deploy.yaml
  mnist/model-train.yaml
Labels: approved, lgtm, size/M
