Repository kubeflow/examples, pull requests merged in 2019-11, with the labels that each got.

#674 Fix the xgboost_synthetic test so it actually runs and produces signal
  py/kubeflow/examples/create_e2e_workflow.py
  xgboost_synthetic/testing/conftest.py
  xgboost_synthetic/testing/job.yaml
  xgboost_synthetic/testing/role.yaml
  xgboost_synthetic/testing/xgboost_test.py
Labels: approved, lgtm, size/L

#675 updates to reflect changed node credentials + minor cleanup
  github_issue_summarization/pipelines/components/kubeflow-resources/tf-serving-gh/tf-serve-template.yaml
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/main.py
  github_issue_summarization/pipelines/components/t2t/webapp-launcher/t2tapp-template.yaml
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/gh_summ_serve.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ_serve.py.tar.gz
Labels: approved, lgtm, size/M

#676 Fix xgboost_synthetic test
  prow_config.yaml
  py/kubeflow/examples/create_e2e_workflow.py
  xgboost_synthetic/testing/conftest.py
  xgboost_synthetic/testing/xgboost_test.py
Labels: approved, lgtm, size/S

#679 pipelines GH summarization example: notebook cleanup
  github_issue_summarization/pipelines/example_pipelines/pipelines-notebook.ipynb
Labels: approved, lgtm, size/XS

#682 Fix issues with the xgboost_synthetic example and deploying the model.
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/notebook_setup.py
Labels: approved, lgtm, size/XL

#683 Add a GitHub action to auto add/remove issues to needs triage kanban board
  .github/workflows/triage_issues.yaml
Labels: approved, lgtm, size/S
