Repository kubeflow/examples, pull requests merged in 2019-10, with the labels that each got.

#651 change gpu limit in example pipeline
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
Labels: approved, lgtm, size/XS

#659 Modify readme to match the actual source code
  pipelines/mnist-pipelines/README.md
Labels: approved, lgtm, ok-to-test, size/S

#660 Fix broken url for example file in simple_pipeline demos
  demos/simple_pipeline/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#666 Update xgboost_synthetic test infra; preliminary updates to work with 0.7.0
  .pylintrc
  prow_config.yaml
  py/README.md
  py/kubeflow/__init__.py
  py/kubeflow/examples/__init__.py
  py/kubeflow/examples/create_e2e_workflow.py
  test/workflows/components/xgboost_synthetic.jsonnet
  xgboost_synthetic/Dockerfile
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/notebook_setup.py
  xgboost_synthetic/testing/conftest.py
  xgboost_synthetic/testing/job.yaml
  xgboost_synthetic/testing/kustomization.yaml
  xgboost_synthetic/testing/params.yaml
  xgboost_synthetic/testing/rolebinding.yaml
  xgboost_synthetic/testing/xgboost_test.py
  xgboost_synthetic/util.py
Labels: approved, lgtm, size/XXL

#669 Updates to the pipelines GH summarization lab to demonstrate component input/output
  github_issue_summarization/pipelines/components/t2t/containers/base/Dockerfile
  github_issue_summarization/pipelines/components/t2t/datacopy_component.yaml
  github_issue_summarization/pipelines/components/t2t/t2t-train/train_model.py
  github_issue_summarization/pipelines/components/t2t/train_component.yaml
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/pipelines-notebook.ipynb
Labels: lgtm, size/L
