Repository kubeflow/examples, pull requests merged in 2019-09, with the labels that each got.

#630 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#599 Added azure pipeline example for Kubeflow
  pipelines/azurepipeline/.gitignore
  pipelines/azurepipeline/README.md
  pipelines/azurepipeline/code/deploy/Dockerfile
  pipelines/azurepipeline/code/deploy/aksdeploymentconfig.json
  pipelines/azurepipeline/code/deploy/build.sh
  pipelines/azurepipeline/code/deploy/deploy.sh
  pipelines/azurepipeline/code/deploy/deploymentconfig.json
  pipelines/azurepipeline/code/deploy/environment.yml
  pipelines/azurepipeline/code/deploy/inference.sh
  pipelines/azurepipeline/code/deploy/inferenceconfig.json
  pipelines/azurepipeline/code/deploy/score.py
  pipelines/azurepipeline/code/pipeline.py
  pipelines/azurepipeline/code/preprocess/Dockerfile
  pipelines/azurepipeline/code/preprocess/Running
  pipelines/azurepipeline/code/preprocess/build.sh
  pipelines/azurepipeline/code/preprocess/data.py
  pipelines/azurepipeline/code/preprocess/requirements.txt
  pipelines/azurepipeline/code/profile/Dockerfile
  pipelines/azurepipeline/code/profile/build.sh
  pipelines/azurepipeline/code/profile/environment.yml
  pipelines/azurepipeline/code/profile/inferenceconfig.json
  pipelines/azurepipeline/code/profile/profile.sh
  pipelines/azurepipeline/code/profile/requirements.txt
  pipelines/azurepipeline/code/profile/score.py
  pipelines/azurepipeline/code/register/Dockerfile
  pipelines/azurepipeline/code/register/build.sh
  pipelines/azurepipeline/code/register/register.py
  pipelines/azurepipeline/code/register/requirements.txt
  pipelines/azurepipeline/code/training/Dockerfile
  pipelines/azurepipeline/code/training/build.sh
  pipelines/azurepipeline/code/training/requirements.txt
  pipelines/azurepipeline/code/training/train.py
  pipelines/azurepipeline/kubernetes/pvc.yaml
Labels: approved, doc-sprint, lgtm, size/XXL

#626 More KF06-related updates to the 'cookbook' branch notebooks
  cookbook/README.md
  cookbook/pipelines/automl/components/dataset_train/dataset_model.py
  cookbook/pipelines/notebooks/README.md
  cookbook/pipelines/notebooks/gcf_kfp_trigger.ipynb
  cookbook/pipelines/notebooks/kfp_remote_deploy-IAP.ipynb
  cookbook/pipelines/notebooks/kfp_remote_deploy-port-forward.ipynb
Labels: approved, lgtm, size/L

#633 Add testing for xgboost_synthetic
  prow_config.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/xgboost_synthetic.jsonnet
  xgboost_synthetic/Makefile
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/requirements.txt
  xgboost_synthetic/testing/execute_notebook.py
  xgboost_synthetic/testing/job.yaml
  xgboost_synthetic/testing/kustomization.yaml
  xgboost_synthetic/testing/params.yaml
  xgboost_synthetic/testing/role.yaml
  xgboost_synthetic/testing/rolebinding.yaml
  xgboost_synthetic/testing/xgboost_test.py
Labels: approved, lgtm, size/XL

#637 update example to use kubeflow-fairing
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/requirements.txt
Labels: approved, lgtm, size/XXL

#590 added named entity recognition example
  README.md
  named_entity_recognition/.gitignore
  named_entity_recognition/README.md
  named_entity_recognition/components/build_components.sh
  named_entity_recognition/components/copy_specification.sh
  named_entity_recognition/components/deploy/Dockerfile
  named_entity_recognition/components/deploy/build_image.sh
  named_entity_recognition/components/deploy/component.yaml
  named_entity_recognition/components/deploy/src/deploy.sh
  named_entity_recognition/components/preprocess/Dockerfile
  named_entity_recognition/components/preprocess/build_image.sh
  named_entity_recognition/components/preprocess/component.yaml
  named_entity_recognition/components/preprocess/src/component.py
  named_entity_recognition/components/preprocess/src/text_preprocessor.py
  named_entity_recognition/components/train/Dockerfile
  named_entity_recognition/components/train/build_image.sh
  named_entity_recognition/components/train/component.yaml
  named_entity_recognition/components/train/src/train.py
  named_entity_recognition/documentation/files/allusers.png
  named_entity_recognition/documentation/files/bucket.png
  named_entity_recognition/documentation/files/container.png
  named_entity_recognition/documentation/files/load-component.png
  named_entity_recognition/documentation/files/metrics.png
  named_entity_recognition/documentation/files/models.png
  named_entity_recognition/documentation/files/monitor-pipeline.png
  named_entity_recognition/documentation/files/permission.png
  named_entity_recognition/documentation/files/predict.png
  named_entity_recognition/documentation/files/result.png
  named_entity_recognition/documentation/files/solution.png
  named_entity_recognition/documentation/step-1-setup.md
  named_entity_recognition/documentation/step-2-build-components.md
  named_entity_recognition/documentation/step-3-upload-dataset.md
  named_entity_recognition/documentation/step-4-custom-prediction-routine.md
  named_entity_recognition/documentation/step-5-run-pipeline.md
  named_entity_recognition/documentation/step-6-monitor-training.md
  named_entity_recognition/documentation/step-7-predictions.md
  named_entity_recognition/notebooks/Pipeline.ipynb
  named_entity_recognition/routine/build_routine.sh
  named_entity_recognition/routine/model_prediction.py
  named_entity_recognition/routine/setup.py
  named_entity_recognition/routine/text_preprocessor.py
Labels: approved, doc-sprint, lgtm, ok-to-test, size/XXL

#642 update component URLs in pipeline definitions
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/gh_summ_preempt.py
Labels: approved, lgtm, size/S

#643 update kubeflow-fairing commit sha to use job in clusterBuild
  xgboost_synthetic/build-train-deploy.ipynb
Labels: approved, lgtm, size/XS

#646 update to kubeflow-metadata in examples
  github_issue_summarization/pipelines/components/t2t/containers/metadata-logger/Dockerfile
  github_issue_summarization/pipelines/components/t2t/metadata-logger/log-metadata.py
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/requirements.txt
Labels: approved, lgtm, size/S
