Repository kubeflow/examples, pull requests merged in 2019-07, with the labels that each got.

#562 minor update to the pachyderm seldon example
  github_issue_summarization/Pachyderm_Example/README.md
  github_issue_summarization/Pachyderm_Example/build.json
Labels: approved, lgtm, ok-to-test, size/M

#584 recomment using kustomize v2.0.3 for mnist
  mnist/README.md
  test/workflows/components/mnist.jsonnet
Labels: approved, lgtm, size/XS

#594 fix e2e test failed problem
  test/workflows/app.yaml
Labels: approved, lgtm, size/XS

#593 remove useless requirements.txt from mnist
  mnist/README.md
  mnist/requirements.txt
Labels: approved, lgtm, size/S

#598 Adding simple pipeline example
  README.md
  pipelines/README.md
  pipelines/simple-notebook-pipeline/README.md
  pipelines/simple-notebook-pipeline/Simple Notebook Pipeline.ipynb
Labels: approved, doc-sprint, lgtm, ok-to-test, size/L

#589 Add kubecon demo to xgboost_ames_housing directory
  xgboost_synthetic/.gitignore
  xgboost_synthetic/Dockerfile
  xgboost_synthetic/Makefile
  xgboost_synthetic/README.md
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/notebook.xgboost-synthetic.yaml
  xgboost_synthetic/requirements.txt
  xgboost_synthetic/util.py
  xgboost_synthetic/xgboost_util.py
Labels: approved, lgtm, ok-to-test, size/XXL

#602 Include newly trained model in the newly built docker image (#601)
  xgboost_synthetic/build-train-deploy.ipynb
Labels: approved, lgtm, size/XS

#603 Install pip dependencies and build base image with kaniko
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/util.py
Labels: approved, lgtm, size/L

#605 Update readme for xgboost-synthetic and remove outdated yaml file
  xgboost_synthetic/README.md
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/notebook.xgboost-synthetic.yaml
Labels: approved, lgtm, size/L

#581 Lint fixes mnist
  .pylintrc
  pytorch_mnist/ks_app/app.yaml
  pytorch_mnist/serving/seldon-wrapper/mnistddpserving.py
  pytorch_mnist/training/ddp/mnist/mnist_DDP.py
Labels: approved, lgtm, size/M

#611 Fix mnist readme service name and deployments name typo
  mnist/README.md
Labels: approved, lgtm, ok-to-test, size/XS
