Repository kubeflow/examples, pull requests merged in 2019-04, with the labels that each got.

#531 fix import issue in the mnist e2e testing
  mnist/testing/deploy_test.py
  mnist/testing/tfjob_test.py
  test/workflows/components/mnist.jsonnet
Labels: approved, lgtm, size/S

#528 Enhance mnist training and add serving steps for local mode
  mnist/README.md
  mnist/ks_app/components/mnist-deploy-local.jsonnet
  mnist/ks_app/components/params.libsonnet
  mnist/ks_app/components/train.jsonnet
Labels: approved, lgtm, size/L

#538 Cleanup the owners file.
  OWNERS
Labels: approved, lgtm, size/XS

#541 Fixed issue with TFJob api version in tfjob component
  object_detection/ks-app/components/params.libsonnet
  object_detection/ks-app/components/tf-training-job.jsonnet
  object_detection/submit_job.md
Labels: approved, lgtm, size/XS

#542 Create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: approved, lgtm, size/XS

#507 import of Pipelines Github issue summarization examples & tutorial
  github_issue_summarization/notebooks/Dockerfile
  github_issue_summarization/notebooks/Dockerfile.estimator
  github_issue_summarization/pipelines/README.md
  github_issue_summarization/pipelines/components/kubeflow-resources/containers/tf-serving-gh/Dockerfile
  github_issue_summarization/pipelines/components/kubeflow-resources/containers/tf-serving-gh/build.sh
  github_issue_summarization/pipelines/components/kubeflow-resources/tf-serving-gh/deploy-tf-serve.py
  github_issue_summarization/pipelines/components/kubeflow-resources/tf-serving-gh/tf-serve-template.yaml
  github_issue_summarization/pipelines/components/t2t/containers/base/Dockerfile
  github_issue_summarization/pipelines/components/t2t/containers/base/build.sh
  github_issue_summarization/pipelines/components/t2t/containers/t2t_app/Dockerfile
  github_issue_summarization/pipelines/components/t2t/containers/t2t_app/build.sh
  github_issue_summarization/pipelines/components/t2t/containers/t2t_proc/Dockerfile
  github_issue_summarization/pipelines/components/t2t/containers/t2t_proc/build.sh
  github_issue_summarization/pipelines/components/t2t/containers/t2t_train/Dockerfile
  github_issue_summarization/pipelines/components/t2t/containers/t2t_train/build.sh
  github_issue_summarization/pipelines/components/t2t/containers/webapp-launcher/Dockerfile
  github_issue_summarization/pipelines/components/t2t/containers/webapp-launcher/build.sh
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/ghsumm/__init__.py
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/ghsumm/setup.py
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/ghsumm/trainer/__init__.py
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/ghsumm/trainer/problem.py
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/github_issues_sample.csv
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/main.py
  github_issue_summarization/pipelines/components/t2t/t2t-app/app/templates/index.html
  github_issue_summarization/pipelines/components/t2t/t2t-proc/ghsumm/__init__.py
  github_issue_summarization/pipelines/components/t2t/t2t-proc/ghsumm/setup.py
  github_issue_summarization/pipelines/components/t2t/t2t-proc/ghsumm/trainer/__init__.py
  github_issue_summarization/pipelines/components/t2t/t2t-proc/ghsumm/trainer/problem.py
  github_issue_summarization/pipelines/components/t2t/t2t-train/ghsumm/__init__.py
  github_issue_summarization/pipelines/components/t2t/t2t-train/ghsumm/setup.py
  github_issue_summarization/pipelines/components/t2t/t2t-train/ghsumm/trainer/__init__.py
  github_issue_summarization/pipelines/components/t2t/t2t-train/ghsumm/trainer/problem.py
  github_issue_summarization/pipelines/components/t2t/t2t-train/train_model.py
  github_issue_summarization/pipelines/components/t2t/webapp-launcher/deploy-webapp.py
  github_issue_summarization/pipelines/components/t2t/webapp-launcher/t2tapp-template.yaml
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/gh_summ_serve.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ_serve.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/pipelines-kubecon.ipynb
  github_issue_summarization/pipelines/tutorial.md
  test/workflows/components/gis.jsonnet
Labels: approved, lgtm, size/XXL
