Repository kubeflow/examples, pull requests merged in 2019-05, with the labels that each got.

#550 Add jinchihe to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#554 [docs]: fix minor bug in the documentation
  mnist/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#556 add missing datagen.py file
  github_issue_summarization/pipelines/components/t2t/t2t-proc/datagen.py
  github_issue_summarization/pipelines/example_pipelines/pipelines-kubecon.ipynb
Labels: approved, lgtm, size/M

#552 Add memory limit
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
Labels: approved, lgtm, size/XS

#555 [docs]: enhance documentation for chosen namespace
  mnist/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#558 Use the client libs to do a GCS copy instead of gsutil
  github_issue_summarization/pipelines/components/t2t/containers/base/Dockerfile
  github_issue_summarization/pipelines/components/t2t/t2t-train/train_model.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/pipelines-kubecon.ipynb
Labels: approved, lgtm, size/L
