Repository kubeflow/examples, pull requests merged in 2019-08, with the labels that each got.

#610 Add metadata logging to xgboost-synthetic example
  xgboost_synthetic/build-train-deploy.ipynb
Labels: approved, lgtm, size/L

#616 Add tensorboard support for local mninst example
  mnist/README.md
  mnist/monitoring/local/deployment_patch.yaml
  mnist/monitoring/local/kustomization.yaml
  mnist/monitoring/local/params.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#618 object_detection: fix typo error in tf-serving.libsonnet
  object_detection/ks-app/vendor/kubeflow/tf-serving/tf-serving.libsonnet
Labels: approved, lgtm, ok-to-test, size/XS

#621 Fix a bunch of issues with the xgboost_synthetic example
  xgboost_synthetic/.gitignore
  xgboost_synthetic/Dockerfile
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/images/addgcpsecret.png
  xgboost_synthetic/requirements.txt
Labels: approved, lgtm, size/XXL

#615 adding automl KFP example to 'cookbook' branch
  cookbook/README.md
  cookbook/pipelines/README.md
  cookbook/pipelines/automl/README.md
  cookbook/pipelines/automl/automl_dataset_and_train.py
  cookbook/pipelines/automl/automl_dataset_and_train.py.tar.gz
  cookbook/pipelines/automl/components/container/Dockerfile
  cookbook/pipelines/automl/components/container/build.sh
  cookbook/pipelines/automl/components/dataset_train/dataset_model.py
  cookbook/pipelines/notebooks/README.md
  cookbook/pipelines/notebooks/gcf_kfp_trigger.ipynb
  cookbook/pipelines/notebooks/kfp_remote_deploy-no-IAP.ipynb
  cookbook/pipelines/notebooks/kfp_remote_deploy.ipynb
Labels: approved, lgtm, size/XL

#625 MNIST: allow extra arguments in model.py
  mnist/model.py
Labels: approved, lgtm, ok-to-test, size/XS
