Repository kubeflow/examples, pull requests merged in 2019-01, with the labels that each got.

#449 Setup continuous building of Docker images for GH Issue Summarization Example
  github_issue_summarization/.gitignore
  github_issue_summarization/Makefile
  github_issue_summarization/image_build.jsonnet
  github_issue_summarization/ks-kubeflow/environments/gh-demo-1003/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/gh-demo-1003/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/gh-demo-1003/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi-test/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi-test/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi-test/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-34c2/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-34c2/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-34c2/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-3f29/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-3f29/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-3f29/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-795b/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-795b/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-795b/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-edb3/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-edb3/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-edb3/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-f96e/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-f96e/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-f96e/params.libsonnet
  github_issue_summarization/ks-kubeflow/lib/ksonnet-lib/v1.11.5/k.libsonnet
  github_issue_summarization/ks-kubeflow/lib/ksonnet-lib/v1.11.5/k8s.libsonnet
  github_issue_summarization/ks-kubeflow/lib/ksonnet-lib/v1.11.5/swagger.json
  github_issue_summarization/ks-kubeflow/lib/v1.10.7/k.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.10.7/k8s.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.10.7/swagger.json
  github_issue_summarization/ks-kubeflow/lib/v1.9.6/k.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.9.6/k8s.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.9.6/swagger.json
  github_issue_summarization/notebooks/Dockerfile
  github_issue_summarization/notebooks/Dockerfile.estimator
  github_issue_summarization/notebooks/train_test.py
  prow_config.yaml
  test/workflows/components/gis.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/environments/test/params.libsonnet
Labels: approved, lgtm, size/XXL

#456 GIS E2E test verify the TFJob runs successfully
  github_issue_summarization/ks-kubeflow/environments/gh-demo-1003/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/gh-demo-1003/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/gh-demo-1003/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi-test/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi-test/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi-test/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/jlewi/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-34c2/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-34c2/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-34c2/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-3f29/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-3f29/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-3f29/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-795b/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-795b/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-795b/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-edb3/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-edb3/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-edb3/params.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-f96e/globals.libsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-f96e/main.jsonnet
  github_issue_summarization/ks-kubeflow/environments/test-env-f96e/params.libsonnet
  github_issue_summarization/ks-kubeflow/lib/ksonnet-lib/v1.11.5/k.libsonnet
  github_issue_summarization/ks-kubeflow/lib/ksonnet-lib/v1.11.5/k8s.libsonnet
  github_issue_summarization/ks-kubeflow/lib/ksonnet-lib/v1.11.5/swagger.json
  github_issue_summarization/ks-kubeflow/lib/v1.10.7/k.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.10.7/k8s.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.10.7/swagger.json
  github_issue_summarization/ks-kubeflow/lib/v1.9.6/k.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.9.6/k8s.libsonnet
  github_issue_summarization/ks-kubeflow/lib/v1.9.6/swagger.json
  github_issue_summarization/ks_app/components/params.libsonnet
  github_issue_summarization/ks_app/components/tfjob.jsonnet
  github_issue_summarization/notebooks/Dockerfile.estimator
  github_issue_summarization/testing/tfjob_test.py
  test/workflows/components/gis.jsonnet
  test/workflows/environments/test/params.libsonnet
Labels: approved, lgtm, size/XXL

#462 Continuously build the docker images used by mnist.
  mnist/.gitignore
  mnist/Makefile
  mnist/image_build.jsonnet
  prow_config.yaml
  test/workflows/components/mnist.jsonnet
  test/workflows/components/params.libsonnet
Labels: approved, lgtm, size/L

#463 [mnist_pytorch] Update documentation
  pytorch_mnist/01_setup_a_kubeflow_cluster.md
  pytorch_mnist/02_distributed_training.md
  pytorch_mnist/03_serving_the_model.md
  pytorch_mnist/README.md
Labels: approved, lgtm, size/S

#465 Update training to use Kubeflow 0.4 and add testing.
  mnist/README.md
  mnist/ks_app/.gitignore
  mnist/ks_app/app.yaml
  mnist/ks_app/components/params.libsonnet
  mnist/ks_app/components/train.jsonnet
  mnist/ks_app/components/util.libsonnet
  mnist/ks_app/environments/base.libsonnet
  mnist/ks_app/environments/jlewi/globals.libsonnet
  mnist/ks_app/environments/jlewi/main.jsonnet
  mnist/ks_app/environments/jlewi/params.libsonnet
  mnist/model.py
  mnist/testing/tfjob_test.py
  test/workflows/components/mnist.jsonnet
  test/workflows/environments/test/params.libsonnet
Labels: approved, lgtm, size/XL

#468 Fix the model training of ames-housing example
  xgboost_ames_housing/Dockerfile
  xgboost_ames_housing/README.md
  xgboost_ames_housing/ames_dataset/data_description.txt
  xgboost_ames_housing/ames_dataset/sample_submission.csv
  xgboost_ames_housing/ames_dataset/test.csv
  xgboost_ames_housing/ames_dataset/train.csv
  xgboost_ames_housing/py-job.yaml
  xgboost_ames_housing/py-pod.yaml
Labels: approved, lgtm, size/XXL

#475 revert back removed v1alpha2 yaml manifests
  pytorch_mnist/02_distributed_training.md
  pytorch_mnist/training/ddp/mnist/cpu/v1alpha2/job_mnist_DDP_CPU.yaml
  pytorch_mnist/training/ddp/mnist/gpu/v1alpha2/job_mnist_DDP_GPU.yaml
Labels: approved, lgtm, size/M

#476 Fix xgboost example for hyperparameter tuning
  xgboost_ames_housing/housing.py
Labels: approved, lgtm, size/S

#470 Add richard and zhenghui to approvers for kubeflow/examples
  xgboost_ames_housing/OWNERS
Labels: approved, lgtm, size/XS

#427 Minor fixes to the notebook.
  code_search/pipeline/CodeSearchPipelineNotebook.ipynb
Labels: approved, lgtm, size/L

#480 [mnist_pytorch] Optimise build and switch backend from MPI to GLOO
  pytorch_mnist/training/ddp/mnist/Dockerfile.traincpu
  pytorch_mnist/training/ddp/mnist/Dockerfile.traingpu
  pytorch_mnist/training/ddp/mnist/mnist_DDP.py
Labels: approved, lgtm, size/L

#472 GitHub Summarization Seldon Update
  github_issue_summarization/03_serving_the_model.md
  github_issue_summarization/notebooks/Makefile
  github_issue_summarization/notebooks/environment_seldon_rest
  github_issue_summarization/notebooks/seq2seq_utils.py
Labels: approved, lgtm, size/L

#482 optimized apt-get to reduce image size
  mnist/Dockerfile.ksonnet
Labels: approved, lgtm, ok-to-test, size/XS

#484 Build images for xgboost-ames-housing
  xgboost_ames_housing/test/Dockerfile.ubuntu-s2i
  xgboost_ames_housing/test/Makefile
  xgboost_ames_housing/test/seldon-image-build.yaml
Labels: approved, lgtm, size/M

#486 Enable periodic tests for mnist & GH issue examples.
  CONTRIBUTING.md
  prow_config.yaml
Labels: approved, lgtm, size/XS

#488 Add support for AWS access/secret keys in the train component (#466)
  mnist/README.md
  mnist/ks_app/components/params.libsonnet
  mnist/ks_app/components/train.jsonnet
  mnist/ks_app/components/util.libsonnet
Labels: approved, lgtm, ok-to-test, size/M
