Repository kubeflow/examples, pull requests merged in 2019-12, with the labels that each got.

#684 Update ci tests for mnist example
  mnist/README.md
  mnist/monitoring/GCS/deployment_patch.yaml
  mnist/monitoring/GCS/kustomization.yaml
  mnist/monitoring/GCS/params.yaml
  mnist/monitoring/base/deployment.yaml
  mnist/serving/GCS/deployment_patch.yaml
  mnist/serving/GCS/kustomization.yaml
  mnist/serving/base/deployment.yaml
  mnist/testing/conftest.py
  mnist/testing/deploy_test.py
  mnist/testing/tfjob_test.py
  mnist/training/GCS/Chief_patch.yaml
  mnist/training/GCS/Ps_patch.yaml
  mnist/training/GCS/Worker_patch.yaml
  mnist/training/GCS/kustomization.yaml
  mnist/training/GCS/params.yaml
  mnist/training/S3/kustomization.yaml
  mnist/training/base/Chief.yaml
  mnist/training/base/Ps.yaml
  mnist/training/base/Worker.yaml
  mnist/training/base/definition.sh
  mnist/training/local/kustomization.yaml
  prow_config.yaml
  py/kubeflow/examples/create_e2e_workflow.py
Labels: approved, lgtm, size/XL

#689 Wrong variable used in the client run example - Cookbook kfp_remote_deploy-IAP
  cookbook/pipelines/notebooks/kfp_remote_deploy-IAP.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#690 Mpi example
  tensorflow-horovod/README.md
  tensorflow-horovod/mpi-job.yaml
Labels: approved, lgtm, size/M

#693 Financial example v0.7
  financial_time_series/.gitignore
  financial_time_series/Financial Time Series with Finance Data.ipynb
  financial_time_series/README.md
  financial_time_series/docs/img/pipeline_graph.png
  financial_time_series/docs/img/pipeline_logs.png
  financial_time_series/docs/img/pipeline_ui.png
  financial_time_series/docs/img/run_metrics.png
  financial_time_series/docs/img/run_with_deploy.png
  financial_time_series/tensorflow_model/CPU/Dockerfile
  financial_time_series/tensorflow_model/CPU/tfjob1.yaml
  financial_time_series/tensorflow_model/CPU/tfjob2.yaml
  financial_time_series/tensorflow_model/CPU/train.jsonnet
  financial_time_series/tensorflow_model/Dockerfile
  financial_time_series/tensorflow_model/GPU/Dockerfile
  financial_time_series/tensorflow_model/GPU/tfjob3.yaml
  financial_time_series/tensorflow_model/GPU/train.jsonnet
  financial_time_series/tensorflow_model/helpers/metrics.py
  financial_time_series/tensorflow_model/helpers/storage.py
  financial_time_series/tensorflow_model/ml_pipeline.py
  financial_time_series/tensorflow_model/requirements.txt
  financial_time_series/tensorflow_model/run_deploy.py
  financial_time_series/tensorflow_model/run_preprocess_train_deploy.py
  financial_time_series/tensorflow_model/run_train.py
  financial_time_series/tensorflow_model/serving_requests/request.py
  financial_time_series/tensorflow_model/serving_requests/request_helper.py
  financial_time_series/tensorflow_model/serving_requests/request_random.py
  financial_time_series/tensorflow_model/tfserving.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#706 Add kubeflow namespace for kubectl commands in Readme for financial t…
  financial_time_series/README.md
Labels: approved, lgtm, ok-to-test, size/S
