Repository kubeflow/examples, pull requests merged in 2019-02, with the labels that each got.

#498 Fixes #497
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#493 Add end2end test for Xgboost housing example
  github_issue_summarization/testing/tfjob_test.py
  mnist/testing/deploy_test.py
  mnist/testing/tfjob_test.py
  mnist/web-ui/mnist_client_test.py
  prow_config.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/xgboost_ames_housing.jsonnet
  test/workflows/environments/test/params.libsonnet
  xgboost_ames_housing/ks_app/.gitignore
  xgboost_ames_housing/ks_app/app.yaml
  xgboost_ames_housing/ks_app/components/params.libsonnet
  xgboost_ames_housing/ks_app/components/seldon.jsonnet
  xgboost_ames_housing/ks_app/components/xgboost.jsonnet
  xgboost_ames_housing/ks_app/environments/base.libsonnet
  xgboost_ames_housing/ks_app/environments/default/globals.libsonnet
  xgboost_ames_housing/ks_app/environments/default/main.jsonnet
  xgboost_ames_housing/ks_app/environments/default/params.libsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/core.libsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/crd.libsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/json/README.md
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/json/pod-template-spec-validation.json
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/json/template_0.1.json
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/json/template_0.2.json
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/parts.yaml
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/abtest-v1alpha1.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/abtest-v1alpha2.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/core.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/mab-v1alpha1.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/mab-v1alpha2.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/outlier-detector-v1alpha1.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/outlier-detector-v1alpha2.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/serve-simple-v1alpha1.jsonnet
  xgboost_ames_housing/ks_app/vendor/kubeflow/seldon/prototypes/serve-simple-v1alpha2.jsonnet
  xgboost_ames_housing/test/Makefile
  xgboost_ames_housing/test/conftest.py
  xgboost_ames_housing/test/predict_test.py
  xgboost_ames_housing/test/query.json
Labels: approved, lgtm, size/XXL

#495 Mnist fixes
  mnist/README.md
  mnist/ks_app/app.yaml
  mnist/ks_app/environments/jlewi/globals.libsonnet
  mnist/ks_app/environments/jlewi/main.jsonnet
  mnist/ks_app/environments/jlewi/params.libsonnet
  mnist/ks_app/environments/test-env-d5e3/globals.libsonnet
  mnist/ks_app/environments/test-env-d5e3/main.jsonnet
  mnist/ks_app/environments/test-env-d5e3/params.libsonnet
Labels: approved, lgtm, ok-to-test, size/L

#399 fixed "setting persistent disk" link
  github_issue_summarization/01_setup_a_kubeflow_cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#508 Fixed typo in README and one bad link
  pytorch_mnist/02_distributed_training.md
  pytorch_mnist/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#477 Update gitignore for all VIM temp files.
  .gitignore
Labels: approved, lgtm, ok-to-test, size/XS

#499 [mnist] Add support for S3 in TensorBoard component; Update docs.
  mnist/README.md
  mnist/ks_app/components/params.libsonnet
  mnist/ks_app/components/tensorboard.jsonnet
  mnist/ks_app/components/train.jsonnet
  mnist/testing/predict_test.py
Labels: lgtm, size/L

#511 Trigger unittests on postsubmit and periodic runs.
  prow_config.yaml
Labels: approved, lgtm, size/XS

#492 Enhance mnist trainer to read args from command line
  mnist/ks_app/components/train.jsonnet
  mnist/model.py
Labels: approved, lgtm, size/L
