Repository kubeflow/examples, pull requests merged in 2019-03, with the labels that each got.

#520 Add Dan Sanche to OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#527 Fixed tf_operator import for github_issue_summarization example
  github_issue_summarization/testing/tfjob_test.py
  test/workflows/components/gis.jsonnet
  test/workflows/components/mnist.jsonnet
Labels: approved, lgtm, size/S

#524 Mnist pipelines
  pipelines/mnist-pipelines/.gitignore
  pipelines/mnist-pipelines/README.md
  pipelines/mnist-pipelines/deploy-service/Dockerfile
  pipelines/mnist-pipelines/deploy-service/src/deploy.sh
  pipelines/mnist-pipelines/img/kubeflow.png
  pipelines/mnist-pipelines/img/logs.png
  pipelines/mnist-pipelines/img/pipeline.png
  pipelines/mnist-pipelines/img/run_form.png
  pipelines/mnist-pipelines/img/upload_btn.png
  pipelines/mnist-pipelines/img/upload_form.png
  pipelines/mnist-pipelines/mnist_pipeline.py
  pipelines/mnist-pipelines/requirements.txt
Labels: approved, lgtm, ok-to-test, size/L

#532 [MNIST Pipeline] Correct some image tags
  pipelines/mnist-pipelines/mnist_pipeline.py
Labels: approved, lgtm, ok-to-test, size/XS
