Repository kubeflow/examples, pull requests merged in 2019-06, with the labels that each got.

#525 initial commit of example showing remote (out of cluster) pipeline deployment
  cookbook/pipelines/notebooks/README.md
  cookbook/pipelines/notebooks/gcf_kfp_trigger.ipynb
  cookbook/pipelines/notebooks/kfp_remote_deploy-no-IAP.ipynb
  cookbook/pipelines/notebooks/kfp_remote_deploy.ipynb
Labels: approved, lgtm, size/XL

#559 Examples for pipelines running on-premise
  pipelines/mnist-pipelines/README.md
  pipelines/mnist-pipelines/img/run_form.png
  pipelines/mnist-pipelines/img/upload_form.png
  pipelines/mnist-pipelines/mnist_pipeline.py
Labels: approved, lgtm, size/M

#568 update TFJob version to v1beta2
  mnist/README.md
  mnist/training/GCS/kustomization.yaml
  mnist/training/S3/kustomization.yaml
  mnist/training/base/Chief.yaml
  mnist/training/base/Ps.yaml
  mnist/training/base/Worker.yaml
  mnist/training/base/definition.sh
  mnist/training/local/kustomization.yaml
Labels: approved, lgtm, size/S

#570 MNIST: Update web-ui reference for GCS
  mnist/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#566 fix issue for s3 case in mnist example
  mnist/training/S3/params.yaml
Labels: approved, lgtm, size/XS

#572 Fixed typo
  mnist/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#490 [pytorch_mnist] Automate image build
  prow_config.yaml
  pytorch_mnist/02_distributed_training.md
  pytorch_mnist/03_serving_the_model.md
  pytorch_mnist/Dockerfile.ksonnet
  pytorch_mnist/Makefile
  pytorch_mnist/image_build.jsonnet
  pytorch_mnist/ks_app/components/params.libsonnet
  pytorch_mnist/ks_app/components/train_model_CPU_v1beta1.jsonnet
  pytorch_mnist/ks_app/components/train_model_CPU_v1beta2.jsonnet
  pytorch_mnist/ks_app/components/train_model_GPU_v1beta1.jsonnet
  pytorch_mnist/ks_app/components/train_model_GPU_v1beta2.jsonnet
  pytorch_mnist/ksonnet-entrypoint.sh
  pytorch_mnist/testing/deploy_test.py
  pytorch_mnist/testing/predict_test.py
  pytorch_mnist/testing/pytorchjob_test.py
  pytorch_mnist/training/ddp/mnist/cpu/v1alpha2/job_mnist_DDP_CPU.yaml
  pytorch_mnist/training/ddp/mnist/cpu/v1beta1/job_mnist_DDP_CPU.yaml
  pytorch_mnist/training/ddp/mnist/gpu/v1alpha2/job_mnist_DDP_GPU.yaml
  pytorch_mnist/training/ddp/mnist/gpu/v1beta1/job_mnist_DDP_GPU.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/pytorch-mnist-cpu-release.jsonnet
  test/workflows/components/pytorch-mnist-gpu-release.jsonnet
  test/workflows/components/pytorch-mnist-serve-release.jsonnet
  test/workflows/components/pytorch-mnist-webui-release.jsonnet
  test/workflows/components/pytorch_mnist.jsonnet
Labels: approved, lgtm, size/XXL

#535 [Financial Time Series] Update example to v0.4.0 and add Kubeflow pipelines
  README.md
  financial_time_series/Financial Time Series with Finance Data.ipynb
  financial_time_series/README.md
  financial_time_series/docs/img/pipeline_ui.png
  financial_time_series/tensorflow_model/CPU/Dockerfile
  financial_time_series/tensorflow_model/CPU/train.jsonnet
  financial_time_series/tensorflow_model/Dockerfile
  financial_time_series/tensorflow_model/GPU/Dockerfile
  financial_time_series/tensorflow_model/GPU/train.jsonnet
  financial_time_series/tensorflow_model/helpers/__init__.py
  financial_time_series/tensorflow_model/helpers/metrics.py
  financial_time_series/tensorflow_model/helpers/models.py
  financial_time_series/tensorflow_model/helpers/preprocess.py
  financial_time_series/tensorflow_model/helpers/storage.py
  financial_time_series/tensorflow_model/ml_pipeline.py
  financial_time_series/tensorflow_model/run_preprocess.py
  financial_time_series/tensorflow_model/run_preprocess_and_train.py
  financial_time_series/tensorflow_model/run_train.py
  financial_time_series/tensorflow_model/serving_requests/request.py
Labels: approved, lgtm, ok-to-test, size/XXL

#573 Add .cache dir to gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#576 fix: update kfp version
  pipelines/mnist-pipelines/requirements.txt
Labels: approved, lgtm, ok-to-test, size/XS

#575 Added a README to the pipelines samples dir
  pipelines/README
Labels: approved, lgtm, size/S

#577 add pipeline section and rename README
  README.md
  pipelines/README.md
Labels: approved, lgtm, size/XS

#579 Add stale bot
  .github/stale.yml
Labels: approved, lgtm, size/S

#582 Add video show notes
  videos/README.md
  videos/from_zero_to_kubeflow/README.md
Labels: approved, lgtm, size/M
