Repository kubeflow/examples, pull requests merged in 2020-03, with the labels that each got.

#756 Tech writing updates for GCP MNIST notebook
  mnist/mnist_gcp.ipynb
Labels: approved, lgtm, size/XL

#744 Update ENTRYPOINT to use /usr/local/bin/python in Dockerfile.model
  mnist/Dockerfile.model
Labels: approved, lgtm, ok-to-test, size/XS

#763 add a general notebook test script
  py/kubeflow/examples/notebook_tests/conftest.py
  py/kubeflow/examples/notebook_tests/nb_test_util.py
  py/kubeflow/examples/notebook_tests/run_notebook_test.py
Labels: approved, lgtm, size/M

#766 Update IBM Cloud mnist instructions to use persistent storage.
  mnist/README.md
Labels: approved, lgtm, size/XS

#769 Update invitation link to Kubeflow Slack channel
  README.md
  github_issue_summarization/Pachyderm_Example/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#771 Clean up of example(simpel notebook)
  pipelines/simple-notebook-pipeline/Simple Notebook Pipeline.ipynb
Labels: approved, lgtm, ok-to-test, size/XS
