Repository kubeflow/examples, pull requests merged in 2020-02, with the labels that each got.

#717 xgboost pin metadata==0.2.0
  xgboost_synthetic/requirements.txt
Labels: approved, lgtm, size/XS

#718 xgboost test for v1
  prow_config.yaml
  py/kubeflow/examples/create_e2e_workflow.py
Labels: approved, lgtm, size/M

#719 Fix namespace test runs
  mnist/testing/conftest.py
  xgboost_synthetic/testing/conftest.py
Labels: approved, lgtm, size/XS

#720 mnist example namespace fix
  mnist/README.md
Labels: approved, lgtm, size/S

#726 add note to indicate that mnist pipeline example does not currently work
  pipelines/mnist-pipelines/README.md
Labels: lgtm, size/XS

#728 Remove the lint tests because they are using python2
  prow_config.yaml
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#735 Write xgboost_synthetic test output to html
  py/kubeflow/examples/create_e2e_workflow.py
  xgboost_synthetic/testing/conftest.py
  xgboost_synthetic/testing/execute_notebook.py
  xgboost_synthetic/testing/xgboost_test.py
Labels: approved, lgtm, size/M

#723 Create a notebook for mnist E2E on GCP
  .pylintrc
  mnist/Dockerfile.model
  mnist/Makefile
  mnist/README.md
  mnist/k8s_util.py
  mnist/mnist_gcp.ipynb
  mnist/monitoring/GCS/kustomization.yaml
  mnist/notebook_setup.py
  mnist/requirements.txt
  mnist/serving/GCS/kustomization.yaml
  mnist/serving/base/mnist-deploy-config.yaml
  mnist/testing/conftest.py
  mnist/testing/deploy_test.py
  mnist/testing/predict_test.py
  mnist/testing/test_data/instances.json
  mnist/testing/tfjob_test.py
  mnist/training/GCS/kustomization.yaml
  mnist/web-ui/mnist_client.py
  prow_config.yaml
  py/kubeflow/examples/create_e2e_workflow.py
  py/kubeflow/examples/notebook_tests/conftest.py
  py/kubeflow/examples/notebook_tests/execute_notebook.py
  py/kubeflow/examples/notebook_tests/job.yaml
  py/kubeflow/examples/notebook_tests/mnist_gcp_test.py
  py/kubeflow/examples/notebook_tests/nb_test_util.py
  test/workflows/components/workflows.libsonnet
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/testing/README.md
Labels: approved, doc-sprint, lgtm, size/XXL

#730 Github action deploy to kubeflow
  pipelines/github_action/README.md
  pipelines/github_action/actions_ower_view.png
  pipelines/github_action/check_action.png
  pipelines/github_action/deep_dive.png
  pipelines/github_action/example_pipeline.py
  pipelines/github_action/example_workflow.yml
  pipelines/github_action/parameters.yaml
Labels: approved, doc-sprint, lgtm, size/L

#736 deprecating gis e2e example until it is fixed.
  github_issue_summarization/README.md
Labels: approved, lgtm, size/XS

#737 Mnist vanilla k8s
  mnist/README.md
  mnist/k8s_util.py
  mnist/mnist_vanilla_k8s.ipynb
  mnist/requirements.txt
Labels: approved, lgtm, size/XXL

#740 Create a notebook for mnist E2E on AWS
  mnist/README.md
  mnist/k8s_util.py
  mnist/mnist_aws.ipynb
  mnist/monitoring/S3/deployment_patch.yaml
  mnist/monitoring/S3/kustomization.yaml
  mnist/monitoring/S3/params.yaml
  mnist/notebook_setup.py
  mnist/serving/S3/deployment_patch.yaml
  mnist/serving/S3/kustomization.yaml
  mnist/serving/S3/params.yaml
  mnist/training/S3/Chief_patch.yaml
  mnist/training/S3/Ps_patch.yaml
  mnist/training/S3/Worker_patch.yaml
  mnist/training/S3/kustomization.yaml
  mnist/training/S3/params.yaml
Labels: approved, lgtm, size/XXL

#745 Remove kustomize from mnist example.
  mnist/Dockerfile.kustomize
  mnist/README.md
  mnist/front/deployment.yaml
  mnist/front/kustomization.yaml
  mnist/front/service.yaml
  mnist/image_build.jsonnet
  mnist/kustomize-entrypoint.sh
  mnist/monitoring/base/deployment.yaml
  mnist/monitoring/base/kustomization.yaml
  mnist/monitoring/base/params.yaml
  mnist/monitoring/base/service.yaml
  mnist/monitoring/local/deployment_patch.yaml
  mnist/monitoring/local/kustomization.yaml
  mnist/monitoring/local/params.yaml
  mnist/serving/base/deployment.yaml
  mnist/serving/base/kustomization.yaml
  mnist/serving/base/mnist-deploy-config.yaml
  mnist/serving/base/params.yaml
  mnist/serving/base/service.yaml
  mnist/serving/local/deployment_patch.yaml
  mnist/serving/local/kustomization.yaml
  mnist/serving/local/params.yaml
  mnist/training/base/Chief.yaml
  mnist/training/base/Ps.yaml
  mnist/training/base/Worker.yaml
  mnist/training/base/definition.sh
  mnist/training/base/kustomization.yaml
  mnist/training/base/params.yaml
  mnist/training/local/Chief_patch.yaml
  mnist/training/local/Ps_patch.yaml
  mnist/training/local/Worker_patch.yaml
  mnist/training/local/kustomization.yaml
  mnist/training/local/params.yaml
Labels: approved, lgtm, size/XXL

#741 Fix the mnist_gcp_test.py
  prow_config.yaml
  py/kubeflow/examples/notebook_tests/execute_notebook.py
  py/kubeflow/examples/notebook_tests/job.yaml
  py/kubeflow/examples/notebook_tests/mnist_gcp_test.py
  py/kubeflow/examples/notebook_tests/nb_test_util.py
  xgboost_synthetic/testing/execute_notebook.py
Labels: approved, lgtm, size/L

#749 GIS KFP example: kfp-related syntax changes; use gcs client libs instead of gsutil
  github_issue_summarization/pipelines/components/t2t/t2t-proc/datagen.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/gh_summ_serve.py
  github_issue_summarization/pipelines/example_pipelines/gh_summ_serve.py.tar.gz
  github_issue_summarization/pipelines/example_pipelines/pipelines-notebook.ipynb
Labels: approved, lgtm, size/M

#746 Add IBM mnist example
  mnist/README.md
  mnist/mnist_ibm.ipynb
  mnist/requirements.txt
Labels: approved, lgtm, size/XL

#758 Update xgboost_synthetic to use metadata SDK 0.3.1
  xgboost_synthetic/build-train-deploy.ipynb
  xgboost_synthetic/requirements.txt
Labels: approved, lgtm, size/XL

#760 Bump notebook image version for xgboost-test
  xgboost_synthetic/testing/conftest.py
  xgboost_synthetic/testing/xgboost_test.py
Labels: approved, lgtm, size/S

#759 Adds MNIST E2E Example for Azure.
  mnist/README.md
  mnist/mnist_azure.ipynb
Labels: approved, lgtm, ok-to-test, size/XL
