Repository kubeflow/examples, pull requests merged in 2020-04, with the labels that each got.

#784 freeze papermill version
  py/kubeflow/examples/notebook_tests/execute_notebook.py
Labels: approved, lgtm, size/XS

#768 Update Azure End to End Example in line with recent docs change
  pipelines/azurepipeline/code/deploy/aksdeploymentconfig.json
  pipelines/azurepipeline/code/deploy/deploy.sh
  pipelines/azurepipeline/code/pipeline.py
  pipelines/azurepipeline/code/preprocess/Dockerfile
  pipelines/azurepipeline/code/profile/Dockerfile
  pipelines/azurepipeline/code/profile/build.sh
  pipelines/azurepipeline/code/profile/environment.yml
  pipelines/azurepipeline/code/profile/inferenceconfig.json
  pipelines/azurepipeline/code/profile/profile.sh
  pipelines/azurepipeline/code/profile/requirements.txt
  pipelines/azurepipeline/code/profile/score.py
  pipelines/azurepipeline/code/register/register.py
  pipelines/azurepipeline/code/training/Dockerfile
  pipelines/azurepipeline/code/training/train.py
Labels: approved, lgtm, ok-to-test, size/L

#791 Add OWNERS file for Azure Pipelines example
  pipelines/azurepipeline/OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#788 Fixes. End-to-End Pipeline Example on Azure
  pipelines/azurepipeline/code/deploy/Dockerfile
  pipelines/azurepipeline/code/deploy/score.py
  pipelines/azurepipeline/code/preprocess/Dockerfile
  pipelines/azurepipeline/code/preprocess/data.py
  pipelines/azurepipeline/code/register/Dockerfile
  pipelines/azurepipeline/code/register/register.py
  pipelines/azurepipeline/code/training/Dockerfile
  pipelines/azurepipeline/code/training/train.py
Labels: approved, lgtm, ok-to-test, size/XL
