Repository kubeflow/examples, pull requests merged in 2020-06, with the labels that each got.

#804 Cleanup the owners file
  OWNERS
Labels: approved, lgtm, size/XS

#803 Some improvements to testing of notebooks
  py/kubeflow/examples/notebook_tests/conftest.py
  py/kubeflow/examples/notebook_tests/nb_test_util.py
  py/kubeflow/examples/notebook_tests/run_notebook_test.py
Labels: approved, lgtm, size/M

#796 Fix typo in Update step-1-setup.md
  named_entity_recognition/documentation/step-1-setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#801 bentoml, fairing, kserving and prophet example
  prophet_bento_timeseries/bentoml-kubeflow-prophet.ipynb
  prophet_bento_timeseries/covid_19_data.csv
Labels: approved, lgtm, size/XXL

#779 Add link to the 'Deploying Kubeflow on GCP' doc
  mnist/mnist_gcp.ipynb
Labels: approved, lgtm, lifecycle/stale, needs-ok-to-test, size/XS
