Repository kubeflow/examples, pull requests merged in 2022-01, with the labels that each got.

#902 Remove outdated video, Add KFP spark example
  kfp-spark/LICENSE
  kfp-spark/README.md
  kfp-spark/images/central-ui.png
  kfp-spark/images/create-run.png
  kfp-spark/images/final-output.png
  kfp-spark/images/pipelines-ui.png
  kfp-spark/images/start_run.png
  kfp-spark/images/upload-pipeline.png
  kfp-spark/k8s-apply-component.yaml
  kfp-spark/k8s-get-component.yaml
  kfp-spark/kubeflow-pipeline.ipynb
  kfp-spark/spark-job.yaml
  kfp-spark/spark-rbac.yaml
  kfp-spark/spark_job_pipeline.yaml
  videos/README.md
  videos/from_zero_to_kubeflow/README.md
Labels: lgtm, approved, size/XL

#909 Add SVM method to Natural Language Processing
  Natural-Language-Processing/1. Install/Install.md
  Natural-Language-Processing/2. Docker/Docker.md
  Natural-Language-Processing/2. Docker/templates/home.html
  Natural-Language-Processing/3. Jupyter Notebook/Cornell-1000-nltk.ipynb
  Natural-Language-Processing/3. Jupyter Notebook/Jupyter Notebook.md
  Natural-Language-Processing/3. Jupyter Notebook/Twitter-5000-nltk.ipynb
  Natural-Language-Processing/3. Jupyter Notebook/cornell-1000.zip
  Natural-Language-Processing/3. Jupyter Notebook/twitter-5000.zip
  Natural-Language-Processing/4. Image/NLP N.png
  Natural-Language-Processing/4. Image/NLP.png
  Natural-Language-Processing/4. Image/compare runs.png
  Natural-Language-Processing/4. Image/cornell-1000 accuracy.png
  Natural-Language-Processing/4. Image/nice to meet you.png
  Natural-Language-Processing/4. Image/nltk.png
  Natural-Language-Processing/4. Image/pipeline.png
  Natural-Language-Processing/4. Image/port forward.png
  Natural-Language-Processing/4. Image/twitter-5000 accuracy.png
  Natural-Language-Processing/README.md
Labels: size/L

#910 Add blog post notice
  README.md
Labels: size/XS
