Repository kubeflow/examples, pull requests merged in 2022-02, with the labels that each got.

#917 Add recurring run demo
  demos/README.md
  demos/recurring/README.md
  demos/recurring/component.yaml
  demos/recurring/download.yaml
  demos/recurring/recurring.ipynb
  demos/recurring/success.sh
  download.yaml
Labels: size/L

#918 Delete download.yaml
  download.yaml
  xgboost_synthetic/README.md
Labels: size/M, approved

#925 Add new owners
  OWNERS
Labels: size/XS, approved

#926 Update OWNERS
  OWNERS
Labels: size/XS
